const duellists: Duellist[] = [
  {
    name: "Tristan Taylor",
    deck: {
      Griggle: 3,
      "The Unhappy Maiden": 3,
      "Sinister Serpent": 3,
      "Milus Radiant": 3,
      "Armed Ninja": 3,
      "Queen's Double": 3,
      "Bone Mouse": 1,
      "Change Slime": 1,
      "Dancing Elf": 3,
      Ooguchi: 3,
      "Key Mace": 1,
      "Steel Scorpion": 3,
      Ameba: 3,
      Bat: 3,
      "Zone Eater": 3,
      "Ancient Jar": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Game Shop",
    payout: 0,
    ante: [],
  },
  {
    name: "Yugi Muto",
    deck: {
      "Gaia the Dragon Champion": 1,
      "Shadow Specter": 3,
      "Mushroom Man": 3,
      "Hane-Hane": 3,
      "Ancient Jar": 3,
      "Curse of Dragon": 1,
      Kuriboh: 3,
      "Gaia The Fierce Knight": 1,
      "Exodia the Forbidden One": 1,
      "Left Arm of the Forbidden One": 1,
      "Right Arm of the Forbidden One": 1,
      "Left Leg of the Forbidden One": 1,
      "Right Leg of the Forbidden One": 1,
      "Skull Servant": 3,
      "Summoned Skull": 1,
      "Dark Magician": 1,
      "Man-Eater Bug": 3,
      Sangan: 1,
      "Monster Reborn": 1,
      "Spellbinding Circle": 2,
      "Horn of the Unicorn": 1,
      "Mystical Moon": 1,
      "Book of Secret Arts": 1,
      Eatgaboon: 1,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Game Shop",
    payout: 0,
    ante: [],
  },
  {
    name: "Joey Wheeler",
    deck: {
      "Battle Warrior": 3,
      "Kagemusha of the Blue Flame": 3,
      "Baby Dragon": 1,
      "Jinzo #7": 3,
      "Time Wizard": 3,
      "The Unhappy Maiden": 3,
      "Mountain Warrior": 3,
      "Flame Swordsman": 1,
      "Magician of Faith": 3,
      "Thousand Dragon": 1,
      "Swordsman of Landstar": 3,
      "Armed Ninja": 3,
      "Dancing Elf": 3,
      "Red-Eyes B. Dragon": 1,
      "Queen's Double": 3,
      "Kunai with Chain": 1,
      Salamandra: 1,
      Eatgaboon: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Game Shop",
    payout: 0,
    ante: [],
  },
  {
    name: "Rebecca",
    deck: {
      "Blast Juggler": 3,
      "Witch of the Black Forest": 1,
      "Vishwar Randi": 2,
      "Cannon Soldier": 1,
      Sangan: 1,
      "Water Element": 3,
      "Mega Thunderball": 3,
      Prisman: 3,
      "Mystical Sheep #1": 3,
      "Djinn the Watcher of the Wind": 3,
      Alinsection: 3,
      "Muse-A": 3,
      "Twin-Headed Thunder Dragon": 1,
      "Millennium Shield": 1,
      "Fiend's Hand": 1,
      "Shadow Ghoul": 1,
      "Mooyan Curry": 1,
      Megamorph: 1,
      "Monster Reborn": 1,
      "Spellbinding Circle": 1,
      "Dark-Piercing Light": 1,
      "Bear Trap": 1,
      "Fake Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Roland",
    deck: {
      Doron: 1,
      "Little Chimera": 1,
      "Milus Radiant": 1,
      "Sinister Serpent": 1,
      "Mask of Darkness": 1,
      "Abyss Flower": 1,
      "Muka Muka": 1,
      "Dharma Cannon": 1,
      "Morphing Jar": 1,
      "Frog the Jam": 1,
      "Penguin Soldier": 1,
      "Pot the Trick": 1,
      "The Last Warrior from Another Planet": 1,
      "Black Luster Soldier": 3,
      "Master of Dragon Soldier": 3,
      "Bolt Escargot": 1,
      "Saber Slasher": 1,
      "Witch's Apprentice": 1,
      "Blue-Eyes Ultimate Dragon": 3,
      "Gale Dogra": 1,
      "Queen's Double": 1,
      "White Dolphin": 1,
      Mechaleon: 1,
      Griggle: 1,
      "Zone Eater": 1,
      "Bone Mouse": 1,
      "Hiro's Shadow Scout": 1,
      "The Unhappy Maiden": 1,
      "Pot of Greed": 1,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Mokuba",
    deck: {
      "Blue-Eyed Silver Zombie": 3,
      "Man-Eating Plant": 3,
      Skelengel: 3,
      "Monster Eye": 3,
      "Jinzo #7": 3,
      Krokodilus: 3,
      "Mechanical Spider": 3,
      "Mystic Lamp": 3,
      Leghul: 3,
      Bat: 3,
      "Witch's Apprentice": 1,
      "Darkness Approaches": 3,
      "Mooyan Curry": 2,
      "House of Adhesive Tape": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Puppeteer of Doom",
    deck: {
      "Megirus Light": 3,
      "Wicked Dragon with the Ersatz Head": 3,
      "Phantom Dewan": 3,
      "Two-Mouth Darkruler": 3,
      "Blue-Eyed Silver Zombie": 3,
      "Needle Ball": 3,
      "Vishwar Randi": 3,
      "Gate Deeg": 3,
      "Doll of Demise": 2,
      Ansatsu: 2,
      "Giant Mech-Soldier": 2,
      "The Last Warrior from Another Planet": 2,
      "Malevolent Nuzzler": 2,
      "Final Flame": 2,
      Yami: 2,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Jinzo",
    deck: {
      "Patrol Robo": 3,
      Prisman: 3,
      "Cyber Jar": 3,
      "Blast Juggler": 3,
      "White Magical Hat": 3,
      "Necrolancer the Timelord": 3,
      "Electric Snake": 3,
      "Turtle Raccoon": 3,
      "Injection Fairy Lily": 3,
      Jinzo: 1,
      "Crow Goblin": 1,
      "Psycho-Puppet": 1,
      "Hiro's Shadow Scout": 3,
      Sparks: 1,
      "Mooyan Curry": 3,
      Hinotama: 1,
      "Machine Conversion Factory": 1,
      "Heavy Storm": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Johnny Steps",
    deck: {
      "Water Omotics": 1,
      "Karate Man": 3,
      "Lady of Faith": 2,
      Arlownay: 3,
      "Muse-A": 3,
      "Goddess of Whim": 3,
      Prisman: 3,
      "Sonic Maid": 3,
      "Rose Spectre of Dunn": 3,
      "Musician King": 3,
      "Witch of the Black Forest": 2,
      "Vishwar Randi": 3,
      "Spirit of the Harp": 1,
      Metalmorph: 3,
      "Goblin Fan": 1,
      "Bear Trap": 1,
      "Reverse Trap": 1,
      "Bad Reaction to Simochi": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Crump",
    deck: {
      "Kappa Avenger": 3,
      Doron: 3,
      "Toad Master": 3,
      "Penguin Soldier": 3,
      Akihiron: 3,
      "Bolt Penguin": 3,
      "Flying Penguin": 3,
      "Twin Long Rods #1": 3,
      "Penguin Torpedo": 3,
      "Penguin Knight": 3,
      Octoberser: 3,
      "Nightmare Penguin": 1,
      Umi: 3,
      "Power of Kaishin": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Strings",
    deck: {
      Monsturtle: 3,
      "Karate Man": 3,
      Akihiron: 3,
      "Barrel Rock": 3,
      "Kappa Avenger": 3,
      "Revival Jam": 3,
      "Humanoid Slime": 3,
      "Frog the Jam": 3,
      "Humanoid Worm Drake": 3,
      "Worm Drake": 3,
      "The Statue of Easter Island": 3,
      Prisman: 3,
      "Power of Kaishin": 2,
      "Invisible Wire": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Galapagos",
    payout: 0,
    ante: [],
  },
  {
    name: "Umbra",
    deck: {
      "Nuvia the Wicked": 3,
      "Tao the Chanter": 3,
      Morinphen: 3,
      Togex: 3,
      "Blue-Eyed Silver Zombie": 3,
      "The Masked Beast": 1,
      "Mask of Darkness": 3,
      "Giant Germ": 3,
      "Shining Abyss": 3,
      "The Statue of Easter Island": 3,
      "Tripwire Beast": 3,
      "Masked Sorcerer": 3,
      "Malevolent Nuzzler": 1,
      "Bear Trap": 1,
      Eatgaboon: 1,
      "Invisible Wire": 1,
    },
    lp: 8000,
    field: "Yami",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Lumis",
    deck: {
      "Mystic Tomato": 3,
      "Stuffed Animal": 3,
      Lisark: 3,
      "Masked Sorcerer": 3,
      "Masked Beast Des Gardius": 1,
      Takuhee: 3,
      "Frenzied Panda": 3,
      "Grand Tiki Elder": 3,
      "Magical Ghost": 3,
      "Mushroom Man #2": 3,
      "Mask of Shine & Dark": 3,
      "Melchid the Four-Face Beast": 3,
      "Malevolent Nuzzler": 1,
      "Dark-Piercing Light": 2,
      "Invisible Wire": 1,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Arkana",
    deck: {
      "Big Eye": 3,
      "Ancient Elf": 3,
      "Legion the Fiend Jester": 3,
      "Fairy's Gift": 3,
      "Mystic Clown": 3,
      "Witty Phantom": 3,
      "Doll of Demise": 3,
      "Dark Magician": 3,
      "The Stern Mystic": 3,
      "Black Pendant": 3,
      "Book of Secret Arts": 3,
      "Beckon to Darkness": 2,
      Yami: 2,
      "Monster Reborn": 1,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Domino Pier",
    payout: 0,
    ante: [],
  },
  {
    name: "Bandit Keith",
    deck: {
      "The Winged Dragon of Ra (Sphere Mode)": 1,
      Metalzoa: 1,
      "Zera The Mant": 1,
      Zoa: 1,
      "Barrel Dragon": 2,
      Seiyaryu: 1,
      "Launcher Spider": 1,
      "Slot Machine": 2,
      "Machine King": 1,
      "Pendulum Machine": 1,
      "Space Megatron": 1,
      Mechanicalchaser: 1,
      "Whiptail Crow": 2,
      "Ryu-Kishin Powered": 3,
      "Blast Sphere": 3,
      "Ryu-Kishin": 2,
      "7 Completed": 3,
      "Brain Control": 1,
      "Change of Heart": 1,
      Metalmorph: 1,
      "Machine Conversion Factory": 3,
      "Monster Reborn": 1,
      "Pot of Greed": 1,
      "Tremendous Fire": 2,
      "Invisible Wire": 3,
    },
    lp: 8000,
    field: "Yami",
    location: "Egypt Exhibition",
    payout: 0,
    ante: [],
  },
  {
    name: "Odion",
    deck: {
      "Mystical Beast Serket": 1,
      "Talons of Shurilane": 3,
      "Embodiment of Apophis": 3,
      "Last Tusk Mammoth": 1,
      "Giant Rex": 1,
      Keldo: 3,
      "Tri-Horned Dragon": 3,
      "Swords of Revealing Light": 3,
      Raigeki: 2,
      "Heavy Storm": 1,
      "Final Destiny": 1,
      "Monster Reborn": 3,
      "Dark Hole": 1,
      "Harpie's Feather Duster": 1,
      "Gravedigger Ghoul": 1,
      "The Inexperienced Spy": 1,
      "Beckon to Darkness": 1,
      "Restructer Revolution": 1,
      "Stop Defense": 1,
      "Acid Trap Hole": 1,
      "Widespread Ruin": 1,
      "Torrential Tribute": 1,
      "Infinite Dismissal": 1,
      "Bear Trap": 1,
      "Amazon Archers": 1,
      "Anti Raigeki": 1,
      "Invisible Wire": 1,
      "Dragon Capture Jar": 1,
      "House of Adhesive Tape": 1,
      Eatgaboon: 1,
      "Goblin Fan": 1,
      "Bad Reaction to Simochi": 1,
      "Reverse Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Egypt",
    payout: 0,
    ante: [],
  },
  {
    name: "Marik Ishtar",
    deck: {
      "Cyber-Tech Alligator": 1,
      "Humanoid Worm Drake": 1,
      "Humanoid Slime": 3,
      "Worm Drake": 3,
      "Executor - Makyura": 3,
      "Revival Jam": 3,
      Newdoria: 3,
      "Viser Des": 3,
      "Darkfire Soldier #1": 2,
      "Talons of Shurilane": 1,
      "Byser Shock": 1,
      "Des Volstgalph": 1,
      "Swords of Revealing Light": 3,
      "Monster Reborn": 3,
      "Soul of the Pure": 2,
      "Harpie's Feather Duster": 1,
      Raigeki: 2,
      "Pot of Greed": 1,
      "Spellbinding Circle": 1,
      "Widespread Ruin": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Egypt",
    payout: 0,
    ante: [],
  },
  {
    name: "Paradox",
    deck: {
      "Boar Soldier": 3,
      "Cyber-Tech Alligator": 1,
      "Gemini Elf": 3,
      "Aqua Dragon": 1,
      "Dark Elf": 3,
      "Tri-Horned Dragon": 1,
      "Flash Assailant": 3,
      "Black Luster Soldier": 3,
      "Zera The Mant": 3,
      "Machine King": 1,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
      "Anti Raigeki": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Dark Mokuba",
    deck: {
      "Gemini Elf": 2,
      "Witty Phantom": 2,
      "Man-Eating Treasure Chest": 2,
      "Darkfire Soldier #1": 2,
      "Skull Red Bird": 2,
      Mechanicalchaser: 2,
      "Dark Zebra": 2,
      "Yamata Dragon": 2,
      "Dragon Seeker": 1,
      "High Tide Gyojin": 3,
      "Talons of Shurilane": 1,
      "Aqua Dragon": 1,
      "Thunder Dragon": 1,
      "Dark Chimera": 1,
      "The Immortal of Thunder": 2,
      "B. Dragon Jungle King": 1,
      "Judge Man": 1,
      "Sky Dragon": 1,
      "Twin-Headed Fire Dragon": 1,
      "Tremendous Fire": 2,
      "Swords of Revealing Light": 3,
      "Dragon Treasure": 2,
      "Gravedigger Ghoul": 1,
      "Widespread Ruin": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Seto Kaiba",
    deck: {
      "Ancient Lamp": 1,
      "Blade Knight": 3,
      "Des Feral Imp": 2,
      "Steel Ogre Grotto #2": 1,
      Swordstalker: 1,
      "Invitation to a Dark Sleep": 3,
      "Blue-Eyes White Dragon": 3,
      "Z-Metal Tank": 3,
      "Vorse Raider": 3,
      "Lord of D.": 1,
      "X-Head Cannon": 3,
      "Y-Dragon Head": 3,
      "Blue-Eyes Ultimate Dragon": 1,
      "Obelisk the Tormentor": 1,
      Megamorph: 3,
      "Crush Card": 2,
      "Heavy Storm": 1,
      "Shadow Spell": 2,
      "Dark Energy": 3,
      "Swords of Revealing Light": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Sol Chevalsky",
    deck: {
      "Thousand-Eyes Restrict": 2,
      Relinquished: 2,
      "Dark-Eyes Illusionist": 1,
      "Toon Dark Magician Girl": 1,
      "Toon Summoned Skull": 1,
      "Rogue Doll": 3,
      "Dark Rabbit": 1,
      "Toon Alligator": 1,
      "Toon Mermaid": 3,
      "Jigen Bakudan": 1,
      "Oscillo Hero #2": 1,
      Bickuribox: 1,
      "Parrot Dragon": 1,
      "Blue-Eyes Toon Dragon": 1,
      "Dragon Piper": 1,
      "Ryu-Ran": 1,
      "Illusionist Faceless Mage": 1,
      "Manga Ryu-Ran": 1,
      "Red Archery Girl": 3,
      "Swords of Revealing Light": 3,
      "Tremendous Fire": 2,
      "Harpie's Feather Duster": 3,
      "Change of Heart": 2,
      "Torrential Tribute": 1,
      "Dragon Capture Jar": 1,
    },
    lp: 20000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Reshef the Dark Being",
    deck: {
      "Vorse Raider": 3,
      Mechanicalchaser: 3,
      "Zombyra the Dark": 2,
      "Nuvia the Wicked": 3,
      "Castle of Dark Illusions": 3,
      "Flash Assailant": 3,
      "Slifer the Sky Dragon": 1,
      "Obelisk the Tormentor": 1,
      "The Winged Dragon of Ra (Battle Mode)": 1,
      "King of Yamimakai": 1,
      "Swords of Revealing Light": 3,
      "Pot of Greed": 3,
      "Harpie's Feather Duster": 2,
      "Monster Reborn": 1,
      Megamorph: 2,
      Raigeki: 1,
      "Change of Heart": 3,
      "Tremendous Fire": 1,
      "Torrential Tribute": 3,
    },
    lp: 40000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Duke Devlin 1",
    deck: {
      "Winged Cleaver": 3,
      "Hourglass of Life": 3,
      "The Bewitching Phantom Thief": 3,
      Firegrass: 3,
      "Serpent Marauder": 3,
      Kaminarikozou: 3,
      "Morphing Jar": 3,
      "Wings of Wicked Flame": 3,
      Meotoko: 3,
      "Phantom Dewan": 3,
      "Wicked Mirror": 3,
      "Boo Koo": 3,
      "Restructer Revolution": 1,
      "The Inexperienced Spy": 1,
      "Heavy Storm": 1,
      "Fake Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Game Shop",
    payout: 0,
    ante: [],
  },
  {
    name: "Duke Devlin 2",
    deck: {
      "Hourglass of Life": 3,
      "The Statue of Easter Island": 2,
      "Orgoth the Relentless": 1,
      Gradius: 3,
      "Weather Control": 3,
      "Fiend's Hand": 3,
      "Spellbinding Circle": 3,
      "Beckon to Darkness": 3,
      "Stop Defense": 3,
      "Cyclon Laser": 3,
      "Machine Conversion Factory": 3,
      "Darkness Approaches": 3,
      Raigeki: 1,
      "Soul of the Pure": 3,
      "Invisible Wire": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Game Shop",
    payout: 0,
    ante: [],
  },
  {
    name: "PaniK 1",
    deck: {
      "Curtain of the Dark Ones": 3,
      Meotoko: 3,
      "Cyber-Stein": 3,
      "The Melting Red Shadow": 3,
      "Fiend's Hand": 3,
      "Phantom Dewan": 3,
      "Mystic Lamp": 3,
      "Saber Slasher": 3,
      "Succubus Knight": 3,
      "Monster Eye": 3,
      "Mooyan Curry": 2,
      "Violet Crystal": 1,
      "Black Pendant": 1,
      "Malevolent Nuzzler": 1,
      Yami: 3,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Duel Express",
    payout: 0,
    ante: [],
  },
  {
    name: "PaniK 2",
    deck: {
      "Dark Assailant": 3,
      Barox: 2,
      "King of Yamimakai": 2,
      "Baron of the Fiend Sword": 3,
      "Castle of Dark Illusions": 1,
      "One Who Hunts Souls": 3,
      "Reaper of the Cards": 2,
      "Metal Guardian": 2,
      "Dark Chimera": 2,
      "Fiend Sword": 3,
      "Dark King of the Abyss": 3,
      "Soul of the Pure": 2,
      "Swords of Revealing Light": 3,
      "Dark Energy": 2,
      "Tremendous Fire": 2,
      Yami: 3,
      "Invisible Wire": 2,
    },
    lp: 15000,
    field: "Yami",
    location: "Pegasus Island",
    payout: 0,
    ante: [],
  },
  {
    name: "Mimic of Doom 1",
    deck: {
      "Invader from Another Dimension": 3,
      "Big Eye": 3,
      "Frenzied Panda": 3,
      Mechaleon: 3,
      "Three-Legged Zombies": 3,
      "Kappa Avenger": 3,
      "Giant Germ": 3,
      Togex: 1,
      Genin: 3,
      "Dream Clown": 3,
      Snakeyashi: 3,
      "Mystical Sheep #1": 3,
      "Talons of Shurilane": 1,
      "Soul Hunter": 1,
      "Final Destiny": 1,
      Ookazi: 1,
      "Mooyan Curry": 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Yami",
    location: "Galapagos",
    payout: 0,
    ante: [],
  },
  {
    name: "Mimic of Doom 2",
    deck: {
      "Dream Clown": 3,
      "Sonic Maid": 3,
      "Rogue Doll": 3,
      "Talons of Shurilane": 3,
      "Dimensional Warrior": 3,
      "Man-Eating Treasure Chest": 3,
      "Musician King": 2,
      "Wall of Illusion": 3,
      "The Judgement Hand": 3,
      "Soul of the Pure": 2,
      "Tremendous Fire": 2,
      Megamorph: 2,
      "Swords of Revealing Light": 3,
      Yami: 3,
      "Invisible Wire": 2,
    },
    lp: 15000,
    field: "Yami",
    location: "Pegasus Island",
    payout: 0,
    ante: [],
  },
  {
    name: "Para 1",
    deck: {
      "Frenzied Panda": 3,
      "Bolt Penguin": 3,
      "Karate Man": 3,
      "Monster Tamer": 2,
      "Barrel Lily": 3,
      Prisman: 3,
      "Nightmare Scorpion": 3,
      "Electric Lizard": 3,
      Alinsection: 3,
      "Electric Snake": 3,
      "Shadow Ghoul": 2,
      "Wall Shadow": 1,
      "Labyrinth Wall": 1,
      "Sanga of the Thunder": 1,
      Cursebreaker: 3,
      "Magical Labyrinth": 3,
    },
    lp: 8000,
    field: "Yami",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Para 2",
    deck: {
      "Jirai Gumo": 2,
      "Karate Man": 3,
      "Frenzied Panda": 3,
      "Monster Tamer": 2,
      "Bolt Penguin": 3,
      Kazejin: 1,
      Suijin: 1,
      "Shadow Ghoul": 2,
      Prisman: 3,
      "Dungeon Worm": 2,
      "Labyrinth Wall": 1,
      "Barrel Lily": 3,
      "Electric Snake": 3,
      "Wall Shadow": 1,
      "Sanga of the Thunder": 1,
      "Gate Guardian": 1,
      "Labyrinth Tank": 1,
      Megamorph: 1,
      Cursebreaker: 2,
      "Magical Labyrinth": 2,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Yami",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Para 3",
    deck: {
      "Mystic Tomato": 3,
      "Sanga of the Thunder": 1,
      "Tripwire Beast": 3,
      "Monster Tamer": 1,
      "The Immortal of Thunder": 3,
      "Destroyer Golem": 3,
      Kojikocy: 3,
      Kazejin: 1,
      "Labyrinth Tank": 1,
      "Wall Shadow": 1,
      "Jirai Gumo": 3,
      "Shadow Ghoul": 1,
      "Dungeon Worm": 1,
      "Labyrinth Wall": 3,
      Suijin: 1,
      "Gate Guardian": 1,
      "Tremendous Fire": 1,
      "Swords of Revealing Light": 3,
      Cursebreaker: 2,
      "Magical Labyrinth": 2,
      "Invisible Wire": 2,
    },
    lp: 15000,
    field: "Yami",
    location: "Dungeon",
    payout: 0,
    ante: [],
  },
  {
    name: "Dox 1",
    deck: {
      "Jirai Gumo": 2,
      "Dragoness the Wicked Knight": 3,
      "Aqua Snake": 3,
      "Monster Tamer": 2,
      "Charubin the Fire Knight": 3,
      Kazejin: 1,
      Suijin: 1,
      "Shadow Ghoul": 2,
      "Princess of Tsurugi": 3,
      "Dungeon Worm": 2,
      "Labyrinth Wall": 1,
      "Root Water": 3,
      "Blast Juggler": 3,
      "Wall Shadow": 1,
      "Sanga of the Thunder": 1,
      "Gate Guardian": 1,
      "Labyrinth Tank": 1,
      Megamorph: 1,
      Cursebreaker: 2,
      "Magical Labyrinth": 2,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Yami",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Dox 2",
    deck: {
      "Skull Red Bird": 3,
      "Sanga of the Thunder": 1,
      "UFO Turtle": 3,
      "Monster Tamer": 1,
      "Darkfire Dragon": 3,
      Lisark: 3,
      "Crazy Fish": 3,
      Kazejin: 1,
      "Labyrinth Tank": 1,
      "Wall Shadow": 1,
      "Jirai Gumo": 3,
      "Shadow Ghoul": 1,
      "Dungeon Worm": 1,
      Suijin: 1,
      "Gate Guardian": 1,
      "Tremendous Fire": 1,
      "Swords of Revealing Light": 3,
      "Labyrinth Wall": 3,
      Cursebreaker: 2,
      "Magical Labyrinth": 2,
      "Invisible Wire": 2,
    },
    lp: 15000,
    field: "Yami",
    location: "Dungeon",
    payout: 0,
    ante: [],
  },
  {
    name: "Jean-Claude Magnum 1",
    deck: {
      "The Bewitching Phantom Thief": 3,
      "Curtain of the Dark Ones": 3,
      "Armed Ninja": 3,
      "Lucky Trinket": 3,
      Genin: 3,
      "Mystic Lamp": 3,
      "Phantom Dewan": 3,
      "Queen's Double": 3,
      "Legendary Sword": 1,
      "Monster Egg": 3,
      "Boo Koo": 3,
      "Djinn the Watcher of the Wind": 3,
      "Sword of Dark Destruction": 1,
      "Black Pendant": 1,
      Eatgaboon: 1,
      "House of Adhesive Tape": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Jean-Claude Magnum 2",
    deck: {
      "Vishwar Randi": 3,
      "Princess of Tsurugi": 3,
      Doron: 3,
      "Karate Man": 3,
      "Hungry Burger": 3,
      "Water Element": 3,
      "Goddess of Whim": 3,
      "Armed Ninja": 3,
      "Muse-A": 3,
      Arlownay: 3,
      "Kagemusha of the Blue Flame": 3,
      "Queen's Double": 3,
      "Bear Trap": 1,
      "Goblin Fan": 1,
      "Reverse Trap": 1,
      "Bad Reaction to Simochi": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Domino Pier",
    payout: 0,
    ante: [],
  },
  {
    name: "Rare Hunter 1",
    deck: {
      "Three-Headed Geedo": 3,
      "Shovel Crusher": 3,
      "Goddess of Whim": 3,
      "Hard Armor": 3,
      "Stone Statue of the Aztecs": 3,
      "Hannibal Necromancer": 3,
      "Exodia the Forbidden One": 3,
      "Left Arm of the Forbidden One": 3,
      "Right Arm of the Forbidden One": 3,
      "Left Leg of the Forbidden One": 3,
      "Right Leg of the Forbidden One": 3,
      "Gear Golem the Moving Fortress": 3,
      "Wood Clown": 3,
      "Pot of Greed": 1,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Rare Hunter 2",
    deck: {
      "Exodia the Forbidden One": 3,
      "Left Arm of the Forbidden One": 3,
      "Right Arm of the Forbidden One": 3,
      "Left Leg of the Forbidden One": 3,
      "Right Leg of the Forbidden One": 3,
      Skelengel: 3,
      "Goddess of Whim": 3,
      "Mysterious Puppeteer": 3,
      Yaranzo: 3,
      "Three-Headed Geedo": 3,
      "Stone Statue of the Aztecs": 3,
      "Gear Golem the Moving Fortress": 3,
      "Hannibal Necromancer": 3,
      "Pot of Greed": 1,
    },
    lp: 8000,
    field: "Yami",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Bonz 1",
    deck: {
      "Wicked Mirror": 3,
      "Fire Reaper": 3,
      "Dragon Zombie": 1,
      "Clown Zombie": 1,
      "Hiro's Shadow Scout": 3,
      "Wood Remains": 3,
      "Needle Ball": 3,
      "The Shadow Who Controls the Dark": 3,
      "Pumpking the King of Ghosts": 1,
      "Blue-Eyed Silver Zombie": 3,
      "Phantom Ghost": 3,
      "Armored Zombie": 1,
      "Crass Clown": 1,
      Zanki: 1,
      "Crawling Dragon": 1,
      Sparks: 2,
      "Violet Crystal": 2,
      "Gravedigger Ghoul": 3,
      Wasteland: 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Italy",
    payout: 0,
    ante: [],
  },
  {
    name: "Bonz 2",
    deck: {
      "Dragon Zombie": 3,
      Skelgon: 2,
      "Temple of Skulls": 3,
      "The Snake Hair": 3,
      "Clown Zombie": 3,
      "Fiend's Hand": 3,
      "Wood Remains": 3,
      "Armored Zombie": 3,
      "Flame Ghost": 3,
      "Pumpking the King of Ghosts": 1,
      "Great Mammoth of Goldfine": 1,
      Wasteland: 3,
      "Gravedigger Ghoul": 3,
      "Violet Crystal": 3,
      "Bear Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Bonz 3",
    deck: {
      "Great Mammoth of Goldfine": 3,
      "Ancient Lamp": 3,
      "Baron of the Fiend Sword": 3,
      "Man-Eating Treasure Chest": 3,
      "Dragon Zombie": 3,
      "Fiend's Hand": 3,
      "The Snake Hair": 3,
      "Clown Zombie": 3,
      "Armored Zombie": 3,
      "Swords of Revealing Light": 3,
      "Violet Crystal": 3,
      "Monster Reborn": 3,
      "Gravedigger Ghoul": 2,
      Wasteland: 2,
      "Acid Trap Hole": 3,
    },
    lp: 8000,
    field: "Wasteland",
    location: "Italy",
    payout: 0,
    ante: [],
  },
  {
    name: "Bonz (Imposter)",
    deck: {
      "Baron of the Fiend Sword": 3,
      "Man-Eating Treasure Chest": 3,
      "Whiptail Crow": 3,
      "Big Eye": 3,
      "Magical Ghost": 3,
      "Dark Assailant": 3,
      Skelgon: 3,
      Barox: 2,
      "Flame Ghost": 3,
      Yaranzo: 3,
      "Mystic Clown": 3,
      "Swords of Revealing Light": 1,
      "Violet Crystal": 2,
      Wasteland: 1,
      "Goblin's Secret Remedy": 1,
      Ookazi: 1,
      "Acid Trap Hole": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Rex Raptor 1",
    deck: {
      "Lesser Dragon": 3,
      "Stone D.": 1,
      Tomozaurus: 3,
      "One-Eyed Shield Dragon": 3,
      Trakadon: 2,
      "Fairy Dragon": 3,
      "Wicked Dragon with the Ersatz Head": 3,
      "Two-Headed King Rex": 1,
      "Petit Dragon": 3,
      "Yamatano Dragon Scroll": 3,
      "Two-Mouth Darkruler": 3,
      "Sword Arm of Dragon": 3,
      Megazowler: 3,
      "Little D": 3,
      "Raise Body Heat": 3,
    },
    lp: 8000,
    field: "Wasteland",
    location: "Canada",
    payout: 0,
    ante: [],
  },
  {
    name: "Rex Raptor 2",
    deck: {
      "Sword Arm of Dragon": 3,
      Uraby: 2,
      Yormungarde: 3,
      Trakadon: 3,
      Pragtical: 2,
      "Darkfire Dragon": 2,
      "Minomushi Warrior": 2,
      "Fairy Dragon": 3,
      "Little D": 3,
      "Destroyer Golem": 2,
      "Two-Headed King Rex": 1,
      "Lesser Dragon": 3,
      Megazowler: 3,
      "Serpent Night Dragon": 2,
      Wasteland: 3,
      "Raise Body Heat": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Rex Raptor 3",
    deck: {
      "Sword Arm of Dragon": 2,
      "Crawling Dragon #2": 3,
      "Blackland Fire Dragon": 2,
      "Koumori Dragon": 2,
      "Darkfire Dragon": 2,
      "Serpent Night Dragon": 2,
      Uraby: 3,
      "Bracchio-raidus": 2,
      Megazowler: 2,
      Pragtical: 1,
      "Swords of Revealing Light": 3,
      Wasteland: 2,
      Megamorph: 3,
      "Pot of Greed": 2,
      "Harpie's Feather Duster": 3,
      "Raise Body Heat": 2,
      "Acid Trap Hole": 3,
    },
    lp: 8000,
    field: "Wasteland",
    location: "Canada",
    payout: 0,
    ante: [],
  },
  {
    name: "Rex Raptor (Imposter)",
    deck: {
      "Darkfire Dragon": 3,
      "The Statue of Easter Island": 3,
      "Bracchio-raidus": 3,
      "Barrel Rock": 3,
      Trakadon: 3,
      "Sky Dragon": 3,
      "Little D": 3,
      "Fairy Dragon": 3,
      "Minomushi Warrior": 3,
      "Destroyer Golem": 3,
      "Lesser Dragon": 2,
      "Swords of Revealing Light": 1,
      "Raise Body Heat": 2,
      Wasteland: 1,
      "Goblin's Secret Remedy": 1,
      Ookazi: 1,
      "Acid Trap Hole": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Weevil Underwood 1",
    deck: {
      "Parasite Paracide": 1,
      "Spiked Snail": 2,
      "Drill Bug": 2,
      Gokibore: 2,
      "Skull-Mark Lady Bug": 1,
      "Giant Flea": 1,
      "Soldier Ari": 2,
      Minar: 2,
      "Larvae Moth": 3,
      "Great Moth": 1,
      "Basic Insect": 3,
      "Killer Needle": 2,
      "Hercules Beetle": 2,
      "Insect Queen": 1,
      "Perfectly Ultimate Great Moth": 1,
      "Big Insect": 2,
      "Flying Kamakiri #1": 1,
      "Nightmare Scorpion": 2,
      "Pinch Hopper": 1,
      "Insect Armor with Laser Cannon": 2,
      "Eradicating Aerosol": 1,
      Forest: 1,
      "Laser Cannon Armor": 2,
      "Infinite Dismissal": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Weevil Underwood 2",
    deck: {
      "Great Moth": 1,
      Gokibore: 2,
      "Flying Kamakiri #2": 2,
      "Cocoon of Evolution": 3,
      "Kuwagata A": 2,
      "Flying Kamakiri #1": 2,
      "Killer Needle": 2,
      "Parasite Paracide": 2,
      "Perfectly Ultimate Great Moth": 1,
      "Kwagar Hercules": 2,
      "Pinch Hopper": 2,
      "Big Insect": 2,
      "Giant Flea": 2,
      "Hunter Spider": 2,
      "Insect Queen": 1,
      "Laser Cannon Armor": 2,
      "Insect Armor with Laser Cannon": 2,
      Forest: 3,
      "Eradicating Aerosol": 2,
      "Invisible Wire": 1,
      "Infinite Dismissal": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Weevil Underwood 3",
    deck: {
      "Larvae Moth": 2,
      "Cocoon of Evolution": 2,
      "Great Moth": 2,
      "Perfectly Ultimate Great Moth": 2,
      "Pinch Hopper": 2,
      "Parasite Paracide": 2,
      "Skull-Mark Lady Bug": 2,
      "Hercules Beetle": 2,
      "Flying Kamakiri #1": 2,
      "Giant Flea": 2,
      "Big Insect": 2,
      Gokibore: 2,
      "Killer Needle": 2,
      "Swords of Revealing Light": 3,
      "Laser Cannon Armor": 3,
      "Eradicating Aerosol": 2,
      "Insect Armor with Laser Cannon": 3,
      "Infinite Dismissal": 3,
    },
    lp: 8000,
    field: "Forest",
    location: "Galapagos",
    payout: 0,
    ante: [],
  },
  {
    name: "Weevil Underwood (Imposter)",
    deck: {
      "Flying Kamakiri #1": 3,
      "Kwagar Hercules": 3,
      "Flying Kamakiri #2": 3,
      "Kuwagata A": 3,
      "Mystic Tomato": 3,
      "Rose Spectre of Dunn": 3,
      "Giant Scorpion of the Tundra": 3,
      "Bean Soldier": 3,
      "Insect Soldiers of the Sky": 2,
      "Drill Bug": 3,
      "Vile Germs": 2,
      "Darkworld Thorns": 3,
      Forest: 1,
      "Swords of Revealing Light": 1,
      "Goblin's Secret Remedy": 1,
      Ookazi: 1,
      "Acid Trap Hole": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Mako Tsunami 1",
    deck: {
      "Sea Kamen": 3,
      "Ice Water": 3,
      "Flying Fish": 3,
      "Beastking of the Swamps": 3,
      "Fiend Kraken": 3,
      Jellyfish: 3,
      "Twin Long Rods #1": 3,
      "The Furious Sea King": 3,
      "The Melting Red Shadow": 3,
      "White Dolphin": 3,
      "Kairyu-Shin": 1,
      "Amphibian Beast": 1,
      "Root Water": 3,
      "Fortress Whale": 1,
      "The Legendary Fisherman": 1,
      "Power of Kaishin": 1,
      Umi: 1,
      "Torrential Tribute": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Mako Tsunami 2",
    deck: {
      "Turtle Bird": 1,
      "The Legendary Fisherman": 1,
      "Fiend Kraken": 3,
      "Flying Fish": 3,
      Jellyfish: 3,
      "Beastking of the Swamps": 3,
      Takriminos: 3,
      "Twin Long Rods #1": 3,
      "Wow Warrior": 3,
      "Amphibian Beast": 1,
      "Kairyu-Shin": 2,
      "Fortress Whale": 1,
      "Amazon of the Seas": 3,
      "Spike Seadra": 1,
      "Boulder Tortoise": 1,
      "Power of Kaishin": 3,
      Umi: 3,
      "Bear Trap": 1,
      "Torrential Tribute": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Mako Tsunami 3",
    deck: {
      "Giant Red Seasnake": 2,
      "Fortress Whale": 2,
      "Fire Kraken": 2,
      "Aqua Serpent": 2,
      "Great White": 2,
      "Crazy Fish": 2,
      "Amphibian Beast": 3,
      Jellyfish: 2,
      "Fiend Kraken": 2,
      "High Tide Gyojin": 2,
      Takriminos: 2,
      "7 Colored Fish": 2,
      "Kairyu-Shin": 2,
      "Swords of Revealing Light": 3,
      "Power of Kaishin": 3,
      Umi: 2,
      "Torrential Tribute": 3,
    },
    lp: 8000,
    field: "Umi",
    location: "Galapagos",
    payout: 0,
    ante: [],
  },
  {
    name: "Mako Tsunami (Imposter)",
    deck: {
      "Crazy Fish": 3,
      "Amazon of the Seas": 3,
      "Water Omotics": 3,
      "Roaring Ocean Snake": 3,
      "Rare Fish": 3,
      "Fire Kraken": 3,
      "Violent Rain": 3,
      "Wow Warrior": 3,
      "High Tide Gyojin": 3,
      "Turtle Bird": 3,
      "Enchanting Mermaid": 2,
      "Goblin's Secret Remedy": 1,
      "Power of Kaishin": 2,
      Umi: 1,
      "Swords of Revealing Light": 1,
      Ookazi: 1,
      "Acid Trap Hole": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Mai Valentine 1",
    deck: {
      "Harpie Lady": 3,
      Mavelus: 3,
      Peacock: 3,
      "Droll Bird": 3,
      "Ray & Temperature": 3,
      Kurama: 3,
      Niwatori: 3,
      "Harpie Lady Sisters": 1,
      "Princess of Tsurugi": 3,
      "Dragoness the Wicked Knight": 2,
      Lisark: 2,
      "Winged Dragon, Guardian of the Fortress #2": 2,
      "Harpie's Pet Dragon": 1,
      "Elegant Egotist": 1,
      "Follow Wind": 1,
      "Cyber Shield": 1,
      Mountain: 1,
      "Electro-Whip": 1,
      "Harpie's Feather Duster": 1,
      "Amazon Archers": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Mai Valentine 2",
    deck: {
      "Sonic Bird": 2,
      "Dragoness the Wicked Knight": 2,
      "Amazon Fighter": 1,
      Peacock: 2,
      Mavelus: 2,
      Takuhee: 2,
      "Kanan the Swordmistress": 2,
      "Winged Dragon, Guardian of the Fortress #2": 2,
      "Harpie Lady Sisters": 1,
      "Amazon Sword Woman": 1,
      "Spirit of the Books": 1,
      "Wing Eagle": 2,
      "Harpie's Pet Dragon": 2,
      Niwatori: 2,
      "Harpie Lady": 3,
      "Fiend Reflection #2": 2,
      "Amazon Chain Master": 1,
      Mountain: 3,
      "Harpie's Feather Duster": 1,
      "Malevolent Nuzzler": 1,
      "Elegant Egotist": 1,
      "Electro-Whip": 1,
      "Cyber Shield": 1,
      "Amazon Archers": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Mai Valentine 3",
    deck: {
      "Skull Red Bird": 2,
      "Crimson Sunbird": 2,
      "Harpie's Brother": 2,
      "Harpie Lady Sisters": 2,
      "Cyber Harpie": 2,
      "Amazon Chain Master": 2,
      "Amazon Sword Woman": 2,
      "Harpie Lady": 2,
      "Harpie's Pet Dragon": 2,
      "Amazon Fighter": 2,
      "Spirit of the Books": 3,
      "Swords of Revealing Light": 3,
      "Cyber Shield": 3,
      "Electro-Whip": 3,
      "Elegant Egotist": 3,
      "Follow Wind": 2,
      "Amazon Archers": 3,
    },
    lp: 8000,
    field: "Mountain",
    location: "Domino Pier",
    payout: 0,
    ante: [],
  },
  {
    name: "Mai Valentine (Imposter)",
    deck: {
      "Skull Red Bird": 3,
      Mavelus: 3,
      "Spirit of the Books": 3,
      "Follow Wind": 2,
      "Senju of the Thousand Hands": 3,
      Skullbird: 3,
      "Fiend Reflection #2": 3,
      "Shining Friendship": 3,
      Takuhee: 3,
      "Faith Bird": 3,
      "Goddess with the Third Eye": 2,
      "Dark Witch": 3,
      "Swords of Revealing Light": 1,
      Ookazi: 1,
      "Goblin's Secret Remedy": 1,
      Mountain: 1,
      "Acid Trap Hole": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Espa Roba 1",
    deck: {
      "Cyber Raider": 3,
      "Oscillo Hero": 3,
      Jinzo: 1,
      "The Last Warrior from Another Planet": 3,
      "UFO Turtle": 3,
      Gradius: 3,
      "Cannon Soldier": 3,
      "The Fiend Megacyber": 1,
      "Ground Attacker Bugroth": 3,
      "Gate Sword": 1,
      "The Inexperienced Spy": 3,
      "Beckon to Darkness": 3,
      "Machine Conversion Factory": 3,
      "Cyclon Laser": 3,
      "Brain Control": 1,
      "Infinite Dismissal": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Espa Roba 2",
    deck: {
      "Axe Raider": 3,
      "Cyber Raider": 3,
      "The Fiend Megacyber": 2,
      "Cyber Falcon": 3,
      "Ground Attacker Bugroth": 3,
      Mechanicalchaser: 2,
      "Guardian of the Throne Room": 3,
      "Reflect Bounder": 3,
      Gradius: 2,
      "Amphibious Bugroth": 3,
      "Swords of Revealing Light": 3,
      "Machine Conversion Factory": 3,
      "Cyclon Laser": 3,
      "Brain Control": 1,
      "Acid Trap Hole": 3,
    },
    lp: 8000,
    field: "Sogen",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Espa Roba (Imposter)",
    deck: {
      "Ground Attacker Bugroth": 3,
      "Guardian of the Throne Room": 3,
      "Amphibious Bugroth": 3,
      "Dimensional Warrior": 3,
      Holograh: 2,
      "Oscillo Hero": 3,
      "Stuffed Animal": 3,
      "Gate Sword": 3,
      Ookazi: 1,
      Kojikocy: 3,
      "Fiend Sword": 3,
      "Cannon Soldier": 3,
      "Swords of Revealing Light": 1,
      Sogen: 1,
      "Goblin's Secret Remedy": 1,
      "Legendary Sword": 1,
      "Sword of Dark Destruction": 1,
      "Acid Trap Hole": 2,
    },
    lp: 10000,
    field: "Yami",
    location: "Pegasus Castle",
    payout: 0,
    ante: [],
  },
  {
    name: "Duel Computer (Novice)",
    deck: {
      "Armed Ninja": 3,
      Ameba: 3,
      "Magician of Faith": 3,
      "Milus Radiant": 2,
      Ooguchi: 2,
      "Pot the Trick": 3,
      "Change Slime": 3,
      "Key Mace": 3,
      Griggle: 3,
      "Queen's Double": 3,
      Bat: 3,
      "Dark Plant": 3,
      "Bone Mouse": 3,
      "Sinister Serpent": 2,
      "The Unhappy Maiden": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Duel Computer (Standard)",
    deck: {
      "Guardian of the Throne Room": 2,
      "Darkfire Soldier #2": 2,
      "The Immortal of Thunder": 2,
      "Alligator's Sword": 2,
      "Battle Ox": 2,
      "Whiptail Crow": 2,
      "Man-Eating Treasure Chest": 2,
      "High Tide Gyojin": 2,
      "Neo the Magic Swordsman": 2,
      "Baron of the Fiend Sword": 2,
      "Cosmo Queen": 1,
      "Judge Man": 1,
      "The Earl of Demise": 1,
      "Mr. Volcano": 1,
      Sengenjin: 1,
      "Sea King Dragon": 1,
      "Garma Sword": 1,
      "Rabid Horseman": 1,
      "Kaminari Attack": 1,
      "Rose Spectre of Dunn": 1,
      "Millennium Golem": 1,
      "Tri-Horned Dragon": 1,
      "Punished Eagle": 1,
      "Talons of Shurilane": 1,
      "Soul of the Pure": 2,
      Ookazi: 2,
      "Acid Trap Hole": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Duel Computer (Expert)",
    deck: {
      "Castle of Dark Illusions": 3,
      "Gemini Elf": 3,
      "Vorse Raider": 3,
      "Dark Elf": 3,
      "Flash Assailant": 3,
      "Blue-Eyes Ultimate Dragon": 1,
      "Blue-Eyes White Dragon": 3,
      "Reflect Bounder": 1,
      "Ancient Lamp": 1,
      "Barrel Dragon": 1,
      "Swords of Revealing Light": 1,
      "Change of Heart": 1,
      "Brain Control": 1,
      "Pot of Greed": 1,
      "Shadow Spell": 2,
      "Beckon to Darkness": 1,
      Megamorph: 1,
      "The Inexperienced Spy": 1,
      "Harpie's Feather Duster": 1,
      "Final Destiny": 1,
      "Crush Card": 1,
      "Torrential Tribute": 1,
      "Widespread Ruin": 2,
      "Amazon Archers": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "KaibaCorp",
    payout: 0,
    ante: [],
  },
  {
    name: "Maximillion Pegasus (HoE)",
    deck: {
      "Thousand-Eyes Restrict": 3,
      "Castle of Dark Illusions": 3,
      "Big Shield Gardna": 3,
      "Toon Summoned Skull": 3,
      "Blue-Eyes Toon Dragon": 3,
      Relinquished: 3,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
    },
    lp: 30000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "Dark Joey (HoE)",
    deck: {
      "Gearfried the Iron Knight": 3,
      "Steel Fan Fighter": 1,
      "Boar Soldier": 3,
      "Panther Warrior": 3,
      "Exarion Universe": 1,
      Jinzo: 1,
      "Red-Eyes B. Dragon": 1,
      "Red-Eyes Black Metal Dragon": 1,
      "B. Skull Dragon": 1,
      "Zombyra the Dark": 3,
      "Gilford the Lightning": 1,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
    },
    lp: 30000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "Yami Bakura (HoE)",
    deck: {
      "Headless Knight": 3,
      "The Earl of Demise": 1,
      "Nuvia the Wicked": 3,
      "The Portrait's Secret": 1,
      "The Gross Ghost of Fled Dreams": 1,
      "Flash Assailant": 3,
      "Dark Elf": 3,
      "Earthbound Spirit": 1,
      "Dark Necrofear": 1,
      Gernia: 1,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
      "Destiny Board": 1,
    },
    lp: 60000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "Yami Yugi (HoE)",
    deck: {
      "Queen's Knight": 3,
      "Jack's Knight": 1,
      "King's Knight": 3,
      "Big Shield Gardna": 3,
      "Dark Elf": 3,
      "Dark Magician": 1,
      "Dark Magician Knight": 1,
      "Dark Magician Girl": 1,
      "Mirage Knight": 1,
      "Dark Flare Knight": 1,
      "Dark Paladin": 1,
      "Flash Assailant": 3,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
    },
    lp: 60000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "Yami Marik (HoE)",
    deck: {
      "Executor - Makyura": 3,
      "Viser Des": 3,
      "Legendary Fiend": 1,
      "Gil Garth": 3,
      "Lava Golem": 1,
      "Dark Jeroid": 3,
      "The Winged Dragon of Ra (Phoenix Mode)": 1,
      Newdoria: 3,
      "Byser Shock": 1,
      Helpoemer: 1,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
    },
    lp: 60000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "Noah (HoE)",
    deck: {
      "Chiron the Mage": 3,
      "Giant Rex": 3,
      "Asura Priest": 3,
      "F.G.D.": 1,
      "Nightmare Penguin": 1,
      Aeris: 3,
      "Berserk Dragon": 1,
      "Yamata Dragon": 1,
      "Perfect Machine King": 1,
      "Shinato, King of a Higher Plane": 1,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
      "Anti Raigeki": 1,
    },
    lp: 60000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "Shadi (HoE)",
    deck: {
      "Dark Elf": 3,
      Sengenjin: 1,
      "Flash Assailant": 3,
      "Gemini Elf": 3,
      "Cosmo Queen": 3,
      "Magician of Black Chaos": 3,
      "Boar Soldier": 3,
      "Bracchio-raidus": 1,
      "Firewing Pegasus": 1,
      "Crimson Sunbird": 1,
      Megamorph: 3,
      "Change of Heart": 3,
      "Harpie's Feather Duster": 3,
      "Monster Reborn": 3,
      "Pot of Greed": 3,
      "Swords of Revealing Light": 3,
      "Torrential Tribute": 3,
      "Anti Raigeki": 1,
    },
    lp: 30000,
    field: "Yami",
    location: "Hall of Eternity",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with the red hat in domino square",
    deck: {
      "Ancient Jar": 3,
      "Shadow Specter": 3,
      "Change Slime": 3,
      "Dark Plant": 3,
      Haniwa: 3,
      "Key Mace": 3,
      "Skull Servant": 3,
      "Steel Scorpion": 3,
      Tomozaurus: 3,
      "Mystic Lamp": 3,
      "Zone Eater": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "other guy in domino square",
    deck: {
      "Dancing Elf": 3,
      Leghul: 3,
      "Jinzo #7": 3,
      Ooguchi: 3,
      "Monster Eye": 3,
      "Armed Ninja": 3,
      "White Dolphin": 3,
      "Turu-Purun": 3,
      "Mechanical Spider": 3,
      Bat: 3,
      "Magician of Faith": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Guy above Domino Square",
    deck: {
      "Zone Eater": 3,
      "Rainbow Flower": 3,
      "Queen's Double": 3,
      "Magician of Faith": 3,
      Haniwa: 3,
      "Mechanical Spider": 3,
      Griggle: 3,
      Leghul: 3,
      "Shadow Specter": 3,
      "Armed Ninja": 3,
      "Dark Plant": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy right of domino square with glasses",
    deck: {
      "Dark Plant": 3,
      "Change Slime": 3,
      "Mechanical Spider": 3,
      "Turu-Purun": 3,
      Ameba: 3,
      "Zone Eater": 3,
      Griggle: 3,
      "Dancing Elf": 3,
      Tomozaurus: 3,
      "Sinister Serpent": 3,
      "Key Mace": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "other guy right of domino square",
    deck: {
      Griggle: 3,
      "Queen's Double": 3,
      "Pot the Trick": 3,
      "Shadow Specter": 3,
      Ameba: 3,
      "Rainbow Flower": 3,
      "Milus Radiant": 3,
      "Bone Mouse": 3,
      "Sinister Serpent": 3,
      "Hane-Hane": 3,
      "Bite Shoes": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy above that area",
    deck: {
      "Bite Shoes": 3,
      "Zone Eater": 3,
      Leghul: 3,
      Griggle: 3,
      "Shadow Specter": 3,
      "Magician of Faith": 3,
      "Milus Radiant": 3,
      "Turu-Purun": 3,
      "Key Mace": 3,
      "Ancient Jar": 3,
      "Change Slime": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with red hair under that area",
    deck: {
      "Queen's Double": 3,
      "Steel Scorpion": 3,
      "Jinzo #7": 3,
      "Mystic Lamp": 3,
      "Skull Servant": 3,
      "Bone Mouse": 3,
      "Ancient Jar": 3,
      "Armed Ninja": 3,
      Ameba: 3,
      "Bite Shoes": 3,
      "Magician of Faith": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "other guy",
    deck: {
      Bat: 3,
      "Mystic Lamp": 3,
      "Dancing Elf": 3,
      Haniwa: 3,
      "Turu-Purun": 3,
      Griggle: 3,
      "Monster Eye": 3,
      Ameba: 3,
      "Ancient Jar": 3,
      "Zone Eater": 3,
      "White Dolphin": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy in area south of clocktower square",
    deck: {
      "Sinister Serpent": 3,
      "Change Slime": 3,
      "Dark Plant": 3,
      "Queen's Double": 3,
      "Hane-Hane": 3,
      "Key Mace": 3,
      Leghul: 3,
      "Milus Radiant": 3,
      "Armed Ninja": 3,
      "Steel Scorpion": 3,
      "Bone Mouse": 3,
      "Fake Trap": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with yellow hair left of that area",
    deck: {
      "Shadow Specter": 3,
      "Rainbow Flower": 3,
      "Magician of Faith": 3,
      "Pot the Trick": 3,
      "Mechanical Spider": 3,
      "Skull Servant": 3,
      Hyozanryu: 3,
      Ooguchi: 3,
      "Bite Shoes": 3,
      Tomozaurus: 3,
      "Jinzo #7": 3,
      "Gravedigger Ghoul": 3,
      "The Inexperienced Spy": 1,
      "Fake Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "train guy #1",
    deck: {
      "Morphing Jar #2": 1,
      "Jinzo #7": 1,
      "Magician of Faith": 1,
      Kaminarikozou: 1,
      "The Bewitching Phantom Thief": 1,
      "The Furious Sea King": 1,
      "Lightning Conger": 1,
      "Wicked Mirror": 1,
      "Weather Control": 1,
      "Mechanical Spider": 1,
      "Dancing Elf": 1,
      "Droll Bird": 1,
      "Curtain of the Dark Ones": 1,
      "Star Boy": 1,
      "Doma The Angel of Silence": 1,
      Tatsunootoshigo: 1,
      Tomozaurus: 1,
      "Flame Dancer": 1,
      "Cyber Commander": 1,
      "Candle of Fate": 1,
      Genin: 1,
      "Mystic Lamp": 1,
      Leogun: 1,
      "Winged Cleaver": 1,
      "Ancient Jar": 1,
      "LaLa Li-oon": 1,
      "Hinotama Soul": 1,
      "Petit Dragon": 1,
      "Armed Ninja": 1,
      "Hane-Hane": 1,
      Peacock: 1,
      "Phantom Dewan": 1,
      "Boo Koo": 1,
      "Monster Eye": 1,
      "Beast of Talwar": 1,
      "Beckon to Darkness": 1,
      "Heavy Storm": 1,
      "Dark-Piercing Light": 1,
      "Restructer Revolution": 1,
      Eatgaboon: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Domino Station",
    payout: 0,
    ante: [],
  },
  {
    name: "guy in same area of train guy #1",
    deck: {
      "Hiro's Shadow Scout": 3,
      "The Melting Red Shadow": 3,
      "Jinzo #7": 3,
      "Cyber-Stein": 3,
      "Air Marmot of Nefariousness": 3,
      "Phantom Dewan": 3,
      Meotoko: 3,
      "Pot the Trick": 3,
      "Mystic Lamp": 3,
      "Curtain of the Dark Ones": 3,
      "Shadow Specter": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with brown (long) hair at train station",
    deck: {
      "Morphing Jar": 3,
      "The Bewitching Phantom Thief": 3,
      "Muka Muka": 3,
      "Key Mace": 3,
      "Weather Control": 3,
      "Boo Koo": 3,
      "Wicked Mirror": 3,
      Haniwa: 3,
      Tomozaurus: 3,
      "Magician of Faith": 3,
      "Ancient Jar": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with black, spikey hair at train station",
    deck: {
      Tomozaurus: 3,
      Korogashi: 3,
      "Ancient Jar": 3,
      "Morphing Jar": 3,
      "Tentacle Plant": 3,
      "Winged Cleaver": 3,
      Haniwa: 3,
      "Gale Dogra": 3,
      "Man-Eater Bug": 3,
      "Muka Muka": 3,
      "Mechanical Spider": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with black hair in a ponytail at train station",
    deck: {
      Kaminarikozou: 3,
      "Candle of Fate": 3,
      Firegrass: 3,
      "Fire Reaper": 3,
      "Petit Dragon": 3,
      "Little Chimera": 3,
      "LaLa Li-oon": 3,
      "Droll Bird": 3,
      "Lightning Conger": 3,
      "Hane-Hane": 3,
      "Hinotama Soul": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "the last guy at train station",
    deck: {
      "Tentacle Plant": 3,
      "Man-Eater Bug": 3,
      "White Dolphin": 3,
      Zarigun: 3,
      "Winged Cleaver": 3,
      "Frog the Jam": 3,
      "Turu-Purun": 3,
      "Gale Dogra": 3,
      Korogashi: 3,
      "Serpent Marauder": 3,
      "Star Boy": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "train guy #2 (at train station)",
    deck: {
      "Morphing Jar": 3,
      "Ancient Jar": 3,
      Tomozaurus: 3,
      "Star Boy": 3,
      "Frog the Jam": 3,
      "Muka Muka": 3,
      "Turu-Purun": 3,
      Zarigun: 3,
      "White Dolphin": 3,
      Haniwa: 3,
      "Serpent Marauder": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy in white shirt in train",
    deck: {
      "Morphing Jar": 3,
      "Boo Koo": 3,
      "Candle of Fate": 3,
      "The Bewitching Phantom Thief": 3,
      "Mystic Lamp": 3,
      "Hane-Hane": 3,
      Korogashi: 3,
      "The Melting Red Shadow": 3,
      "Frog the Jam": 3,
      "Lightning Conger": 3,
      "Kaiser Dragon": 1,
      "Meteor Dragon": 1,
      "Meteor B. Dragon": 1,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "other guy in train",
    deck: {
      "Petit Dragon": 3,
      "Little Chimera": 3,
      "Droll Bird": 3,
      LaMoon: 1,
      "Weather Control": 3,
      Kaminarikozou: 3,
      "The Bewitching Phantom Thief": 3,
      "Key Mace": 3,
      "Hane-Hane": 3,
      "Wicked Mirror": 3,
      "LaLa Li-oon": 3,
      "Bolt Escargot": 1,
      Ocubeam: 1,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "train guy #3 (in train)",
    deck: {
      LaMoon: 1,
      Genin: 3,
      Kanikabuto: 3,
      Kiseitai: 3,
      "Turtle Raccoon": 3,
      "Monster Egg": 3,
      Ganigumo: 3,
      "Dig Beak": 3,
      "Djinn the Watcher of the Wind": 3,
      "Stone D.": 1,
      "Petit Angel": 3,
      "Lucky Trinket": 3,
      "Darkness Approaches": 3,
      "Saber Slasher": 1,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Duel Express",
    payout: 0,
    ante: [],
  },
  {
    name: "girl in suite back in train",
    deck: {
      "Droll Bird": 3,
      "White Dolphin": 3,
      "Turu-Purun": 3,
      "Hourglass of Life": 1,
      "Weather Control": 3,
      "Petit Dragon": 3,
      "Boo Koo": 3,
      "Time Wizard": 3,
      "Magician of Faith": 3,
      Haniwa: 3,
      Kaminarikozou: 3,
      "Air Marmot of Nefariousness": 3,
      "Key Mace": 3,
      "Phantom Dewan": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "father of the girl",
    deck: {
      "Ryu-Kishin": 3,
      "The Bewitching Phantom Thief": 3,
      "Pot the Trick": 3,
      "Morphing Jar #2": 3,
      "Silver Bow and Arrow": 1,
      "White Magical Hat": 3,
      "Cyber Jar": 3,
      "Blue-Eyed Silver Zombie": 3,
      Prisman: 3,
      "Blast Juggler": 3,
      "Bite Shoes": 3,
      Mikazukinoyaiba: 1,
      Leogun: 1,
      Ocubeam: 1,
      "Pot of Greed": 1,
      "Horn of Light": 1,
      "Black Pendant": 1,
      "Violet Crystal": 1,
      "Dragon Treasure": 1,
      Eatgaboon: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Kaiba-imitating guy",
    deck: {
      "White Dolphin": 3,
      "Sinister Serpent": 3,
      Tomozaurus: 3,
      "Emperor of the Land and Sea": 1,
      "Petit Dragon": 3,
      "LaLa Li-oon": 3,
      Kaminarikozou: 3,
      "Serpent Marauder": 3,
      "Armed Ninja": 3,
      "Queen's Double": 3,
      "Droll Bird": 3,
      Trent: 1,
      "Spike Seadra": 1,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "man at train station",
    deck: {
      "Petit Dragon": 3,
      "Flame Dancer": 3,
      "Turu-Purun": 3,
      "The Melting Red Shadow": 3,
      "Weather Control": 3,
      Tomozaurus: 3,
      "LaLa Li-oon": 3,
      "Gale Dogra": 3,
      "Mystic Lamp": 3,
      "Wicked Mirror": 3,
      "Monster Eye": 3,
      "Darkness Approaches": 3,
      "Anti Raigeki": 3,
      "House of Adhesive Tape": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Takeshi (Domino Pier)",
    deck: {
      "Morphing Jar": 1,
      "Wicked Mirror": 1,
      "Serpent Marauder": 1,
      "Little Chimera": 1,
      "Star Boy": 1,
      Zarigun: 1,
      "Candle of Fate": 1,
      "Petit Dragon": 1,
      "Fiend's Hand": 1,
      "Frog the Jam": 1,
      "LaLa Li-oon": 1,
      Hoshiningen: 1,
      Kaminarikozou: 1,
      "Witch's Apprentice": 1,
      "Tentacle Plant": 1,
      "Curtain of the Dark Ones": 1,
      "Cyber-Stein": 1,
      "Boo Koo": 1,
      "The Melting Red Shadow": 1,
      "Phantom Dewan": 1,
      "Hourglass of Life": 1,
      Meotoko: 1,
      "Wings of Wicked Flame": 1,
      "Gale Dogra": 1,
      "Flame Dancer": 1,
      Firegrass: 1,
      "The Bewitching Phantom Thief": 1,
      "Fire Reaper": 1,
      "Basic Insect": 1,
      "Man-Eater Bug": 1,
      "Hiro's Shadow Scout": 1,
      "Winged Cleaver": 1,
      Haniwa: 1,
      "Droll Bird": 1,
      "Hinotama Soul": 1,
      "Turu-Purun": 1,
      "Hane-Hane": 1,
      "The Inexperienced Spy": 1,
      "Pot of Greed": 1,
      Eatgaboon: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Domino Pier",
    payout: 0,
    ante: [],
  },
  {
    name: "Woman (Domino Pier)",
    deck: {
      "Wicked Mirror": 3,
      "Bite Shoes": 3,
      "Hiro's Shadow Scout": 3,
      "Dancing Elf": 3,
      Kiseitai: 3,
      "Weather Control": 3,
      "The Shadow Who Controls the Dark": 3,
      "Candle of Fate": 3,
      "Happy Lover": 3,
      "Needle Ball": 3,
      "Key Mace": 3,
      "Winged Trumpeter": 2,
      "Malevolent Nuzzler": 2,
      "Exile of the Wicked": 2,
      Eatgaboon: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy in canada (not in the cave) on the far left",
    deck: {
      Dissolverock: 3,
      "Cyber Jar": 3,
      "Morphing Jar #2": 3,
      Prisman: 3,
      "Rock Ogre Grotto #1": 3,
      Haniwa: 3,
      "Stone Ogre Grotto": 1,
      "Barrel Rock": 3,
      "Morphing Jar": 3,
      "Millennium Golem": 1,
      "Mystical Sand": 1,
      "Muka Muka": 3,
      "Rock Ogre Grotto #2": 3,
      "Stone D.": 1,
      Invigoration: 3,
      Eatgaboon: 2,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "other guy in canada outside the cave",
    deck: {
      "Mega Thunderball": 3,
      "Electric Lizard": 3,
      "Ray & Temperature": 3,
      "Nightmare Scorpion": 3,
      "LaLa Li-oon": 3,
      "Petit Dragon": 3,
      Prisman: 3,
      "Djinn the Watcher of the Wind": 3,
      "Stone Ogre Grotto": 1,
      "Stone D.": 1,
      "Mountain Warrior": 3,
      "Thunder Dragon": 1,
      Ocubeam: 1,
      Invigoration: 3,
      "Gravedigger Ghoul": 3,
      Eatgaboon: 2,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Guy with red hair in area left",
    deck: {
      "Electric Snake": 3,
      Wetha: 3,
      "Kaminari Attack": 3,
      "Oscillo Hero #2": 3,
      "Toad Master": 3,
      "The Furious Sea King": 3,
      "Turtle Bird": 3,
      "Electric Lizard": 3,
      "Water Element": 3,
      Monsturtle: 3,
      "Crab Turtle": 3,
      "Twin Long Rods #1": 3,
      "Power of Kaishin": 1,
      Umi: 1,
      Invigoration: 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Other guy",
    deck: {
      "Super War-Lion": 3,
      Fusionist: 3,
      "Dungeon Worm": 2,
      Alinsection: 3,
      "Laughing Flower": 3,
      Snakeyashi: 3,
      "Insect Soldiers of the Sky": 3,
      "Mystical Sheep #2": 3,
      "Man-Eating Plant": 3,
      Trent: 2,
      "Flower Wolf": 2,
      "Nightmare Scorpion": 3,
      Minar: 3,
      "Beast Fangs": 1,
      "Vile Germs": 1,
      Forest: 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Guy dressed in blue",
    deck: {
      "Mega Thunderball": 3,
      "Droll Bird": 3,
      Peacock: 2,
      "Oscillo Hero #2": 3,
      "Wicked Dragon with the Ersatz Head": 3,
      "Serpent Marauder": 3,
      "Petit Dragon": 3,
      "Electric Snake": 3,
      Kurama: 3,
      Niwatori: 3,
      "Bolt Escargot": 2,
      "Sky Dragon": 2,
      "Twin-Headed Thunder Dragon": 3,
      "Dragon Treasure": 1,
      "Follow Wind": 1,
      Mountain: 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "guy with yellow hair and glasses in area right",
    deck: {
      "Koumori Dragon": 3,
      "The Wicked Worm Beast": 3,
      "Rude Kaiser": 1,
      "Tiger Axe": 3,
      "Zombie Warrior": 3,
      "Ryu-Kishin": 3,
      "Blackland Fire Dragon": 3,
      "Winged Dragon, Guardian of the Fortress #1": 3,
      Garoozis: 1,
      "Battle Steer": 1,
      "The Last Warrior from Another Planet": 1,
      "Mountain Warrior": 3,
      Ansatsu: 1,
      "Sword Hunter": 1,
      "Hitotsu-Me Giant": 3,
      "Zombyra the Dark": 1,
      "Succubus Knight": 1,
      "Axe of Despair": 1,
      Sogen: 1,
      "Sword of Dark Destruction": 1,
      "Legendary Sword": 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Area above guy",
    deck: {
      Zoa: 3,
      "Necrolancer the Timelord": 3,
      "Djinn the Watcher of the Wind": 3,
      Sangan: 3,
      "Needle Ball": 3,
      Nemuriko: 3,
      "Flame Manipulator": 3,
      Morinphen: 3,
      "Giant Germ": 3,
      "Mask of Darkness": 3,
      "Ryu-Kishin": 3,
      "Musician King": 3,
      Yami: 1,
      "Black Pendant": 1,
      "Malevolent Nuzzler": 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Guy with red hair in area right-under",
    deck: {
      "Princess of Tsurugi": 3,
      "Battle Steer": 3,
      "Zombie Warrior": 3,
      "Lava Battleguard": 3,
      "Mountain Warrior": 3,
      "M-Warrior #1": 3,
      "Monster Egg": 3,
      "Swamp Battleguard": 3,
      "Garnecia Elefantis": 3,
      Doron: 3,
      "Battle Warrior": 3,
      "M-Warrior #2": 3,
      "Sword of Dark Destruction": 1,
      "Legendary Sword": 1,
      Sogen: 1,
      "Bear Trap": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "1 of those guys in Canada",
    deck: {
      "Mystical Sand": 2,
      Prisman: 3,
      Trakadon: 3,
      "Two-Mouth Darkruler": 3,
      "Zombie Warrior": 3,
      Uraby: 3,
      "Great Mammoth of Goldfine": 2,
      "Little D": 3,
      Tomozaurus: 2,
      "The Statue of Easter Island": 3,
      Yaranzo: 3,
      "Bracchio-raidus": 2,
      Invigoration: 1,
      "Mooyan Curry": 2,
      Wasteland: 1,
      "Raise Body Heat": 1,
      "Bear Trap": 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Woman in Ship",
    deck: {
      Sangan: 3,
      "Invader from Another Dimension": 3,
      "Muse-A": 3,
      "Goddess with the Third Eye": 3,
      "Dark King of the Abyss": 3,
      "Goddess of Whim": 3,
      Skelengel: 3,
      "Winged Trumpeter": 2,
      "Versago the Destroyer": 3,
      "Mask of Darkness": 3,
      "Happy Lover": 3,
      "Ray & Temperature": 3,
      "Malevolent Nuzzler": 2,
      Megamorph: 1,
      "Invisible Wire": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Man in Ship",
    deck: {
      "Cosmo Queen": 1,
      "Javelin Beetle": 1,
      "Skull Guardian": 1,
      Chakra: 1,
      "Water Omotics": 1,
      "Hitotsu-Me Giant": 1,
      "Fiend Reflection #1": 1,
      "Fiend's Mirror": 1,
      Yamadron: 1,
      "Performance of Sword": 1,
      "Millennium Shield": 1,
      "Mountain Warrior": 1,
      "Mask of Darkness": 1,
      "Crab Turtle": 1,
      "Super War-Lion": 1,
      "Hungry Burger": 1,
      Dokurorider: 1,
      "Versago the Destroyer": 1,
      "M-Warrior #1": 1,
      "Queen of Autumn Leaves": 1,
      "Succubus Knight": 1,
      "Temple of Skulls": 1,
      "Mask of Shine & Dark": 1,
      "Zera The Mant": 1,
      "Serpent Night Dragon": 1,
      "One-Eyed Shield Dragon": 1,
      "Tri-Horned Dragon": 1,
      "Mysterious Puppeteer": 1,
      "Ryu-Kishin Powered": 1,
      "Psycho-Puppet": 1,
      "Garma Sword": 1,
      Leogun: 1,
      "Darkfire Dragon": 1,
      "Hercules Beetle": 1,
      Sengenjin: 1,
      "30,000-Year White Turtle": 1,
      "B. Dragon Jungle King": 1,
      Megamorph: 1,
      "Invisible Wire": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Guy-imitating Kaiba at Egyptian Exhibition",
    deck: {
      Dissolverock: 3,
      "Giant Germ": 3,
      Doron: 3,
      "Wicked Dragon with the Ersatz Head": 3,
      "Mystical Sheep #2": 3,
      "Kairyu-Shin": 1,
      Prisman: 3,
      "Goddess of Whim": 3,
      "Reaper of the Cards": 1,
      "Insect Soldiers of the Sky": 3,
      "Nimble Momonga": 3,
      Trent: 1,
      "Oscillo Hero #2": 3,
      "Talons of Shurilane": 1,
      "Yamata Dragon": 1,
      "Spirit of the Mountain": 1,
      Megamorph: 2,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Egypt Exhibition",
    payout: 0,
    ante: [],
  },
  {
    name: "Monkey #1",
    deck: {
      "Bolt Penguin": 3,
      "Blast Juggler": 3,
      "Shovel Crusher": 3,
      Lisark: 3,
      "Toad Master": 3,
      "Patrol Robo": 3,
      "Nekogal #1": 3,
      "Cyber Commander": 3,
      "Witch of the Black Forest": 3,
      "Mystical Sheep #1": 3,
      Holograh: 3,
      "Frenzied Panda": 3,
      Raigeki: 1,
      "Dark Hole": 1,
      "Heavy Storm": 1,
      "Final Destiny": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Monkey #2",
    deck: {
      "Bolt Penguin": 3,
      "Blast Juggler": 3,
      "Shovel Crusher": 3,
      Lisark: 3,
      "Toad Master": 3,
      "Patrol Robo": 3,
      "Nekogal #1": 3,
      "Cyber Commander": 3,
      "Witch of the Black Forest": 3,
      "Mystical Sheep #1": 3,
      Holograh: 3,
      "Frenzied Panda": 3,
      Hinotama: 1,
      "Final Flame": 1,
      Ookazi: 1,
      "Tremendous Fire": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Monkey #3",
    deck: {
      "Bolt Penguin": 3,
      "Blast Juggler": 3,
      "Shovel Crusher": 3,
      Lisark: 3,
      "Toad Master": 3,
      "Patrol Robo": 3,
      "Nekogal #1": 3,
      "Cyber Commander": 3,
      "Witch of the Black Forest": 3,
      "Mystical Sheep #1": 3,
      Holograh: 3,
      "Frenzied Panda": 3,
      "Bear Trap": 1,
      "Invisible Wire": 1,
      "Acid Trap Hole": 1,
      "Widespread Ruin": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Monkey #4",
    deck: {
      Griggle: 3,
      "The Unhappy Maiden": 3,
      "Sinister Serpent": 3,
      "Milus Radiant": 3,
      "Armed Ninja": 3,
      "Queen's Double": 3,
      "Bone Mouse": 1,
      "Change Slime": 1,
      "Dancing Elf": 3,
      Ooguchi: 3,
      "Key Mace": 1,
      "Steel Scorpion": 3,
      Ameba: 3,
      Bat: 3,
      "Zone Eater": 3,
      "Ancient Jar": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul left of Rex (Canada)",
    deck: {
      "Horn Imp": 3,
      Solitude: 3,
      "Saber Slasher": 1,
      "Stuffed Animal": 3,
      "Giant Germ": 3,
      "Clown Zombie": 3,
      "Mystic Clown": 3,
      "Claw Reacher": 3,
      Zoa: 1,
      "Succubus Knight": 1,
      "Versago the Destroyer": 3,
      "Fiend Sword": 3,
      "Dark King of the Abyss": 3,
      Hinotama: 2,
      "Red Medicine": 2,
      "Black Pendant": 1,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Canada",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul right of Rex (Canada)",
    deck: {
      "The Judgement Hand": 3,
      Holograh: 3,
      "Oscillo Hero": 3,
      "Sonic Maid": 3,
      "Ancient Elf": 3,
      Mikazukinoyaiba: 1,
      "Fiend Reflection #1": 3,
      "Crass Clown": 3,
      "Maiden of the Moonlight": 3,
      "White Magical Hat": 3,
      "Mystical Sheep #1": 3,
      "Ill Witch": 1,
      "Talons of Shurilane": 1,
      "Red Medicine": 2,
      "Bright Castle": 1,
      Hinotama: 2,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Canada",
    payout: 0,
    ante: [],
  },
  {
    name: "First Ghoul (Duel Express)",
    deck: {
      Takuhee: 3,
      "Dark King of the Abyss": 3,
      "Nimble Momonga": 3,
      Trakadon: 3,
      "The Judgement Hand": 3,
      "Ice Water": 3,
      "Drill Bug": 3,
      "Giant Germ": 3,
      "Oscillo Hero": 3,
      Ansatsu: 2,
      "Sword Hunter": 1,
      "Aqua Snake": 3,
      "Red Medicine": 2,
      Hinotama: 2,
      "Beast Fangs": 1,
      "Bear Trap": 2,
    },
    lp: 2000,
    field: "Yami",
    location: "Duel Express",
    payout: 0,
    ante: [],
  },
  {
    name: "Second Ghoul (Duel Express)",
    deck: {
      "Claw Reacher": 3,
      "One Who Hunts Souls": 3,
      Yaranzo: 3,
      "Skull Knight": 2,
      "Ogre of the Black Shadow": 3,
      "Witch of the Black Forest": 3,
      Solitude: 3,
      "Dark King of the Abyss": 3,
      "Warrior of Tradition": 2,
      "Gate Sword": 2,
      "Koumori Dragon": 3,
      "Witty Phantom": 3,
      Hinotama: 2,
      "Dark Energy": 1,
      "Red Medicine": 2,
      "Bear Trap": 2,
    },
    lp: 2000,
    field: "Yami",
    location: "Duel Express",
    payout: 0,
    ante: [],
  },
  {
    name: "Third Ghoul (Duel Express)",
    deck: {
      "Invader from Another Dimension": 3,
      "Talons of Shurilane": 2,
      "White Magical Hat": 3,
      "Fiend Reflection #1": 3,
      "Fiend Reflection #2": 3,
      "Oscillo Hero": 3,
      Seiyaryu: 2,
      "Ancient Elf": 3,
      "Musician King": 2,
      "Mystical Sheep #1": 3,
      "Sonic Maid": 3,
      "The Judgement Hand": 3,
      Hinotama: 2,
      "Red Medicine": 2,
      "Bright Castle": 1,
      "Bear Trap": 2,
    },
    lp: 2000,
    field: "Yami",
    location: "Duel Express",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Outside Duel Express)",
    deck: {
      "Flame Ghost": 3,
      "Turtle Bird": 2,
      Lisark: 3,
      "Flame Manipulator": 3,
      "Charubin the Fire Knight": 3,
      "Vermillion Sparrow": 2,
      Takuhee: 3,
      "Flying Kamakiri #1": 3,
      Kurama: 3,
      Fireyarou: 3,
      "Launcher Spider": 2,
      "Dragoness the Wicked Knight": 3,
      Hinotama: 2,
      Invigoration: 1,
      "Red Medicine": 2,
      "Bear Trap": 2,
    },
    lp: 2000,
    field: "Yami",
    location: "Egypt Exhibition",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Egyptian Exhibition)",
    deck: {
      "Mushroom Man #2": 3,
      "Electric Lizard": 3,
      "Tripwire Beast": 3,
      "Bean Soldier": 3,
      "Electric Snake": 3,
      "Frenzied Panda": 3,
      "Mega Thunderball": 3,
      "Kaminari Attack": 2,
      "Wood Remains": 3,
      "Bolt Penguin": 3,
      "Leopard Girl": 2,
      "Twin-Headed Thunder Dragon": 2,
      Invigoration: 1,
      Hinotama: 2,
      "Red Medicine": 2,
      "Bear Trap": 2,
    },
    lp: 2000,
    field: "Yami",
    location: "Egypt Exhibition",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino City - right-under left)",
    deck: {
      "Dark King of the Abyss": 3,
      "Megirus Light": 3,
      "Big Eye": 3,
      "Wicked Mirror": 3,
      "Ryu-Kishin": 3,
      "Beast of Talwar": 1,
      "Needle Ball": 3,
      "The Shadow Who Controls the Dark": 3,
      "Hiro's Shadow Scout": 3,
      "Versago the Destroyer": 3,
      "Monster Eye": 2,
      "Candle of Fate": 2,
      Morinphen: 1,
      Hinotama: 2,
      "Red Medicine": 2,
      "Malevolent Nuzzler": 1,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino City - right-under right)",
    deck: {
      "Hitotsu-Me Giant": 3,
      "The Last Warrior from Another Planet": 1,
      Prisman: 3,
      Solitude: 3,
      "One Who Hunts Souls": 3,
      "M-Warrior #1": 3,
      "Dragoness the Wicked Knight": 3,
      Garoozis: 1,
      Doron: 2,
      "M-Warrior #2": 3,
      "Karate Man": 3,
      Ansatsu: 1,
      "Axe of Despair": 1,
      "Vishwar Randi": 3,
      "Battle Steer": 1,
      "Red Medicine": 2,
      Hinotama: 2,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino City - under Clock Tower Square)",
    deck: {
      Lisark: 2,
      "Winged Dragon, Guardian of the Fortress #2": 3,
      Wilmee: 2,
      Mavelus: 2,
      "Mystical Sheep #2": 2,
      "Silver Fang": 2,
      Wolf: 2,
      "Frenzied Panda": 2,
      Torike: 2,
      Niwatori: 3,
      "Nekogal #1": 3,
      Fusionist: 2,
      "Super War-Lion": 2,
      Peacock: 2,
      Tatsunootoshigo: 2,
      Hinotama: 2,
      "Red Medicine": 2,
      "Mystical Moon": 1,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino City - left-under)",
    deck: {
      "Kappa Avenger": 3,
      "Aqua Snake": 3,
      "Penguin Knight": 3,
      "Oscillo Hero #2": 3,
      Fireyarou: 3,
      "Fire Eye": 3,
      "Twin-Headed Thunder Dragon": 1,
      "Flame Champion": 1,
      "Charubin the Fire Knight": 3,
      "Electric Snake": 3,
      "Bolt Escargot": 1,
      "Electric Lizard": 3,
      Octoberser: 1,
      Hinotama: 2,
      "Gravedigger Ghoul": 2,
      Invigoration: 1,
      "Red Medicine": 2,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino City - right-up)",
    deck: {
      "Little D": 3,
      Mechaleon: 3,
      "Wicked Dragon with the Ersatz Head": 3,
      "Lesser Dragon": 3,
      "Two-Mouth Darkruler": 3,
      "Fairy Dragon": 3,
      "Yamatano Dragon Scroll": 3,
      "Serpent Marauder": 3,
      "Petit Dragon": 3,
      "B. Dragon Jungle King": 1,
      "Sword Arm of Dragon": 1,
      "Sky Dragon": 1,
      Mikazukinoyaiba: 1,
      "Red Medicine": 2,
      Hinotama: 2,
      "Gravedigger Ghoul": 2,
      "Dragon Treasure": 1,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino City - Clock Tower Square)",
    deck: {
      "Temple of Skulls": 3,
      Skelgon: 3,
      "Zombie Warrior": 3,
      "Dokuroizo the Grim Reaper": 3,
      "Dark Assailant": 3,
      "Wood Remains": 3,
      "Flame Ghost": 3,
      "Blue-Eyed Silver Zombie": 3,
      "Fire Reaper": 2,
      "Fiend's Hand": 2,
      "Three-Legged Zombies": 3,
      "Violet Crystal": 1,
      Hinotama: 2,
      "Gravedigger Ghoul": 2,
      "Red Medicine": 2,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul at Bonz",
    deck: {
      "Ice Water": 2,
      "Ill Witch": 1,
      Prisman: 2,
      "Succubus Knight": 1,
      "Amazon of the Seas": 2,
      "Mystic Tomato": 2,
      Arlownay: 2,
      "Nekogal #1": 2,
      "Mystical Sand": 1,
      "Leopard Girl": 1,
      "Bear Trap": 2,
      "Hungry Burger": 1,
      "Goddess of Whim": 2,
      "Water Omotics": 2,
      "Mushroom Man": 2,
      "Sonic Maid": 2,
      "Enchanting Mermaid": 2,
      "Bean Soldier": 2,
      "Rainbow Marine Mermaid": 1,
      "Rose Spectre of Dunn": 1,
      "Nekogal #2": 1,
      LaMoon: 1,
      "Black Pendant": 1,
      Hinotama: 2,
      "Red Medicine": 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Italy",
    payout: 0,
    ante: [],
  },
  {
    name: "Ghoul (Domino Station)",
    deck: {
      Kumootoko: 3,
      Armaill: 3,
      "Hard Armor": 3,
      "Musician King": 3,
      "Ancient Tree of Enlightenment": 3,
      "Armored Starfish": 3,
      "Giant Rat": 3,
      "Boulder Tortoise": 1,
      Hyozanryu: 2,
      "Skull-Mark Lady Bug": 3,
      "30,000-Year White Turtle": 1,
      "Total Defense Shogun": 1,
      "Darkfire Dragon": 3,
      "Queen Bird": 1,
      Hinotama: 2,
      "Red Medicine": 2,
      "Steel Shell": 1,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Yami",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian (Egyptian Exhibition)",
    deck: {
      "Mystical Sheep #2": 3,
      LaMoon: 3,
      "Goddess of Whim": 3,
      "Hourglass of Life": 3,
      "The Bewitching Phantom Thief": 3,
      Genin: 3,
      "Happy Lover": 3,
      "Necrolancer the Timelord": 3,
      "Muse-A": 3,
      "Wicked Mirror": 3,
      Mikazukinoyaiba: 1,
      "Bright Castle": 1,
      "Red Medicine": 2,
      "Lucky Trinket": 3,
      "Black Pendant": 1,
      Eatgaboon: 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Egypt Exhibition",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian (Domino Pier)",
    deck: {
      Morinphen: 1,
      "Hiro's Shadow Scout": 3,
      Genin: 3,
      "Candle of Fate": 3,
      "Djinn the Watcher of the Wind": 3,
      "Boo Koo": 3,
      "Flame Manipulator": 3,
      "Claw Reacher": 3,
      "White Magical Hat": 3,
      "Giant Germ": 3,
      "Needle Ball": 3,
      "Necrolancer the Timelord": 3,
      "Spirit of the Mountain": 1,
      "Beast of Talwar": 1,
      "Exile of the Wicked": 1,
      "Restructer Revolution": 1,
      "Last Day of Witch": 1,
      Eatgaboon: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Domino Pier",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian (Italy)",
    deck: {
      "Wicked Dragon with the Ersatz Head": 3,
      "Goddess of Whim": 3,
      "Toad Master": 3,
      "Muse-A": 3,
      "Necrolancer the Timelord": 3,
      "Electric Snake": 3,
      "Thunder Dragon": 1,
      "Nightmare Scorpion": 3,
      "Princess of Tsurugi": 3,
      "Electric Lizard": 3,
      Dissolverock: 2,
      "Two-Mouth Darkruler": 3,
      "Stone D.": 1,
      "Succubus Knight": 1,
      "Red Medicine": 2,
      Eatgaboon: 3,
    },
    lp: 8000,
    field: "Arena",
    location: "Italy",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian (China)",
    deck: {
      "Karate Man": 3,
      "Flame Manipulator": 3,
      "Electric Snake": 3,
      Kurama: 3,
      "Frenzied Panda": 3,
      "Nimble Momonga": 3,
      "Steel Fan Fighter": 1,
      "Metal Dragon": 1,
      Alinsection: 3,
      Holograh: 3,
      "Mystical Sheep #1": 3,
      Solitude: 3,
      Minar: 3,
      "Thunder Dragon": 1,
      "Red Medicine": 2,
      "Bear Trap": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian (Canada)",
    deck: {
      "Mystical Sheep #1": 3,
      "Nekogal #1": 2,
      "Wicked Dragon with the Ersatz Head": 3,
      "Djinn the Watcher of the Wind": 3,
      "Twin-Headed Thunder Dragon": 1,
      "Electric Snake": 3,
      "Sword Hunter": 1,
      Ansatsu: 1,
      Wetha: 3,
      "Aqua Snake": 3,
      "Muse-A": 3,
      "Zombie Warrior": 3,
      "The Statue of Easter Island": 1,
      "Crawling Dragon": 1,
      Morinphen: 1,
      Akihiron: 1,
      "Malevolent Nuzzler": 2,
      Sparks: 2,
      "Black Pendant": 2,
      "Heavy Storm": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Canada",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian #1 (China)",
    deck: {
      "Darkfire Dragon": 3,
      "The Stern Mystic": 3,
      Takriminos: 3,
      "Maiden of the Moonlight": 3,
      Kuriboh: 3,
      "Tri-Horned Dragon": 1,
      "Faith Bird": 3,
      Seiyaryu: 1,
      "Crab Turtle": 1,
      "Zera The Mant": 1,
      "The Immortal of Thunder": 3,
      "Rare Fish": 3,
      "Skull Knight": 1,
      Sengenjin: 1,
      "Cosmo Queen": 1,
      "Restructer Revolution": 3,
      Multiply: 3,
      Yami: 3,
    },
    lp: 3000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian #2 (China)",
    deck: {
      "Darkfire Dragon": 3,
      "Dark Magician": 3,
      "Cosmo Queen": 1,
      "The Immortal of Thunder": 3,
      "Maiden of the Moonlight": 3,
      Takriminos: 3,
      "Time Wizard": 3,
      "Baby Dragon": 3,
      "The Stern Mystic": 3,
      "Rare Fish": 3,
      "Faith Bird": 3,
      "Tri-Horned Dragon": 1,
      Sengenjin: 1,
      "Zera The Mant": 1,
      "Restructer Revolution": 3,
      Yami: 3,
    },
    lp: 3000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian #3 (China)",
    deck: {
      "Maiden of the Moonlight": 3,
      "The Stern Mystic": 3,
      "Faith Bird": 3,
      Takriminos: 3,
      "The Wicked Worm Beast": 3,
      "Rare Fish": 3,
      "The Immortal of Thunder": 3,
      "Cosmo Queen": 1,
      Trakadon: 3,
      "Tri-Horned Dragon": 1,
      "Darkfire Dragon": 3,
      "The Judgement Hand": 3,
      Seiyaryu: 1,
      "Zera The Mant": 1,
      "Skull Knight": 1,
      "Crab Turtle": 1,
      Sengenjin: 1,
      "Restructer Revolution": 3,
    },
    lp: 3000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian #4 (China)",
    deck: {
      "Maiden of the Moonlight": 3,
      "The Immortal of Thunder": 3,
      "Darkfire Dragon": 3,
      "Celtic Guardian": 3,
      "Faith Bird": 3,
      Sengenjin: 1,
      "Zera The Mant": 1,
      Takriminos: 3,
      "The Stern Mystic": 3,
      "Rare Fish": 3,
      Seiyaryu: 1,
      "Tri-Horned Dragon": 1,
      "Skull Knight": 1,
      "Crab Turtle": 1,
      "Cosmo Queen": 1,
      "Restructer Revolution": 3,
      Sogen: 3,
      "Legendary Sword": 3,
    },
    lp: 3000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Millennium Guardian #5 (China)",
    deck: {
      "Curse of Dragon": 3,
      "Winged Dragon, Guardian of the Fortress #1": 3,
      Takriminos: 3,
      "Rare Fish": 3,
      "Maiden of the Moonlight": 3,
      "The Immortal of Thunder": 3,
      "Darkfire Dragon": 3,
      "The Stern Mystic": 3,
      "Blackland Fire Dragon": 3,
      "Faith Bird": 3,
      "Gaia The Fierce Knight": 3,
      "Gaia the Dragon Champion": 1,
      Mountain: 3,
      "Restructer Revolution": 3,
    },
    lp: 3000,
    field: "Arena",
    location: "China",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevaliers (Pegasus' Island - Cable Car)",
    deck: {
      "Maha Vailo": 2,
      "Mushroom Man #2": 2,
      "Talons of Shurilane": 1,
      "Minomushi Warrior": 2,
      "Maiden of the Moonlight": 2,
      "Darkfire Dragon": 2,
      "Mother Grizzly": 2,
      Takuhee: 2,
      "Magical Ghost": 2,
      "Rainbow Marine Mermaid": 1,
      "Dark King of the Abyss": 2,
      "Tripwire Beast": 2,
      Togex: 1,
      "Metal Dragon": 1,
      "Crow Goblin": 1,
      "Dice Armadillo": 1,
      "Musician King": 1,
      Spikebot: 1,
      Skelgon: 1,
      "Swords of Revealing Light": 1,
      Ookazi: 1,
      Sogen: 1,
      Umi: 1,
      Wasteland: 1,
      "Goblin's Secret Remedy": 1,
      Forest: 1,
      Mountain: 1,
      Yami: 1,
      "Invisible Wire": 2,
    },
    lp: 10000,
    field: "Arena",
    location: "Pegasus Island",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #1 (The Dungeon - Western Path)",
    deck: {
      "Minomushi Warrior": 3,
      "Karbonala Warrior": 3,
      "Mystic Horseman": 3,
      "Tripwire Beast": 3,
      "Breath of Light": 1,
      "Kaminari Attack": 3,
      "Steel Ogre Grotto #2": 2,
      "Giant Flea": 3,
      "The Immortal of Thunder": 3,
      "Nekogal #2": 3,
      "Twin-Headed Thunder Dragon": 1,
      "Empress Judge": 1,
      "Flame Cerebrus": 1,
      "Warrior Elimination": 1,
      Ookazi: 1,
      "Eternal Rest": 1,
      "Exile of the Wicked": 1,
      "Last Day of Witch": 1,
      "Eradicating Aerosol": 1,
      "Swords of Revealing Light": 1,
      "Goblin's Secret Remedy": 1,
      "Eternal Drought": 1,
      "Stain Storm": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #1 (The Dungeon - Eastern Path)",
    deck: {
      "Breath of Light": 1,
      "Darkfire Dragon": 3,
      "Flying Kamakiri #2": 3,
      Grappler: 3,
      Lisark: 3,
      "Armored Lizard": 3,
      Fireyarou: 3,
      "Flame Champion": 3,
      "Deepsea Shark": 3,
      Skullbird: 3,
      "Roaring Ocean Snake": 1,
      "Punished Eagle": 1,
      Ookazi: 1,
      "Goblin's Secret Remedy": 1,
      "Swords of Revealing Light": 1,
      "Warrior Elimination": 1,
      "Eternal Rest": 1,
      "Exile of the Wicked": 1,
      "Last Day of Witch": 1,
      "Eradicating Aerosol": 1,
      "Eternal Drought": 1,
      "Stain Storm": 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #2 (The Dungeon - Western Path)",
    deck: {
      "Maiden of the Moonlight": 3,
      "Oscillo Hero": 3,
      "Fiend Reflection #1": 3,
      "Talons of Shurilane": 1,
      "Sea King Dragon": 2,
      "Man-Eating Treasure Chest": 3,
      "High Tide Gyojin": 3,
      "Mystical Sheep #1": 3,
      "Water Omotics": 3,
      "Violent Rain": 3,
      "Enchanting Mermaid": 3,
      Grappler: 3,
      Ookazi: 2,
      "Goblin's Secret Remedy": 2,
      "Swords of Revealing Light": 1,
      "Invisible Wire": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #2 (The Dungeon - Eastern Path)",
    deck: {
      "Karate Man": 3,
      "Kanan the Swordmistress": 2,
      Holograh: 3,
      Mikazukinoyaiba: 1,
      "Sword Hunter": 1,
      "Maha Vailo": 3,
      "Destroyer Golem": 3,
      "The Statue of Easter Island": 3,
      "Shining Friendship": 3,
      "Ancient Elf": 3,
      "White Magical Hat": 3,
      Torike: 3,
      "Millennium Golem": 1,
      "Dark Witch": 1,
      "Swords of Revealing Light": 1,
      Ookazi: 2,
      "Goblin's Secret Remedy": 2,
      "Invisible Wire": 2,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #3 (The Dungeon - Western Path)",
    deck: {
      "Darkfire Dragon": 3,
      Fireyarou: 3,
      "Magical Ghost": 3,
      "The Last Warrior from Another Planet": 1,
      "Metal Dragon": 1,
      "Fire Kraken": 3,
      "Whiptail Crow": 3,
      Lisark: 3,
      Takuhee: 3,
      "Skull Red Bird": 3,
      "Stuffed Animal": 2,
      "Giant Mech-Soldier": 1,
      "Cannon Soldier": 3,
      "Turtle Bird": 1,
      Ookazi: 2,
      "Goblin's Secret Remedy": 2,
      "Swords of Revealing Light": 1,
      "Invisible Wire": 2,
    },
    lp: 10000,
    field: "Mountain",
    location: "Dungeon",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #3 (The Dungeon - Eastern Path)",
    deck: {
      "Dark King of the Abyss": 3,
      "Giant Germ": 2,
      "Bolt Penguin": 3,
      "Ushi Oni": 1,
      "Twin-Headed Thunder Dragon": 1,
      "The Immortal of Thunder": 3,
      "Baron of the Fiend Sword": 3,
      "Versago the Destroyer": 3,
      "Tripwire Beast": 3,
      "Mystic Tomato": 3,
      "Nimble Momonga": 3,
      "Kuwagata A": 3,
      "Leopard Girl": 1,
      "Warrior of Tradition": 1,
      Ookazi: 2,
      "Goblin's Secret Remedy": 2,
      "Swords of Revealing Light": 1,
      "Invisible Wire": 2,
    },
    lp: 10000,
    field: "Mountain",
    location: "Dungeon",
    payout: 0,
    ante: [],
  },
  {
    name: "Chevalier #4 (The Dungeon - Western/Eastern Path)",
    deck: {
      "Ground Attacker Bugroth": 2,
      "Man-Eating Treasure Chest": 2,
      "Skull Knight": 1,
      "Talons of Shurilane": 1,
      "The Immortal of Thunder": 2,
      "Rare Fish": 2,
      "Fiend Sword": 2,
      "Roaring Ocean Snake": 1,
      "Firewing Pegasus": 1,
      "Flame Cerebrus": 1,
      "Mystic Clown": 2,
      "Darkfire Soldier #2": 2,
      "Earthbound Spirit": 1,
      "Mushroom Man #2": 2,
      "Skull Red Bird": 2,
      "Guardian of the Throne Room": 2,
      Mikazukinoyaiba: 1,
      "Twin-Headed Thunder Dragon": 1,
      "Sky Dragon": 1,
      "Swords of Revealing Light": 1,
      "Goblin's Secret Remedy": 2,
      Ookazi: 2,
      Forest: 1,
      Yami: 1,
      Wasteland: 1,
      Mountain: 1,
      Umi: 1,
      Sogen: 1,
    },
    lp: 8000,
    field: "Arena",
    location: "Clock Tower Square",
    payout: 0,
    ante: [],
  },
];

export default duellists;
