const routeDuellists = [
  "train guy #1",
  "train guy #3 (in train)",
  "PaniK 1",
  "Millennium Guardian (Egyptian Exhibition)",
  "Duel Computer (Novice)",
  "Puppeteer of Doom",
  "Jean-Claude Magnum 1",
  "Millennium Guardian (Domino Pier)",
  "Bonz 1",
  "Millennium Guardian (Italy)",
  "Para 1",
  "Para 2",
  "Dox 1",
  "Millennium Guardian (China)",
  "Jinzo",
  "Rex Raptor 1",
  "Millennium Guardian (Canada)",
  "Mimic of Doom 1",
  "Rare Hunter 1",
  "Ghoul at Bonz",
  "Ghoul right of Rex (Canada)",
  "Ghoul left of Rex (Canada)",
  "Strings",
  "Lumis",
  "Umbra",
  "Arkana",
  "Rare Hunter 2",
  "First Ghoul (Duel Express)",
  "Second Ghoul (Duel Express)",
  "Third Ghoul (Duel Express)",
  "Ghoul (Outside Duel Express)",
  "Ghoul (Egyptian Exhibition)",
  "Bandit Keith",
  "Marik Ishtar",
  "Millennium Guardian #1 (China)",
  "Millennium Guardian #2 (China)",
  "Millennium Guardian #3 (China)",
  "Millennium Guardian #4 (China)",
  "Millennium Guardian #5 (China)",
  "Paradox",
  "Chevaliers (Pegasus' Island - Cable Car)",
  "PaniK 2",
  "Mimic of Doom 2",
  "Chevalier #3 (The Dungeon - Western Path)",
  "Chevalier #3 (The Dungeon - Eastern Path)",
  "Para 3",
  "Dox 2",
  "Bonz 3",
  "Rex Raptor 3",
  "Weevil Underwood 3",
  "Mako Tsunami 3",
  "Mai Valentine 3",
  "Espa Roba 2",
  "Bonz (Imposter)",
  "Rex Raptor (Imposter)",
  "Weevil Underwood (Imposter)",
  "Mako Tsunami (Imposter)",
  "Mai Valentine (Imposter)",
  "Espa Roba (Imposter)",
  "Dark Mokuba",
  "Seto Kaiba",
  "Sol Chevalsky",
  "Reshef the Dark Being",
];

export default routeDuellists;
