const routeDuellists = [
  "Player (Initial Deck)",
  "Player (Initial Trunk)",
  "Conductor (Turnstyles)",
  "Conductor (Carriage)",
  "PaniK 1",
  "Millennium Guardian (Egyptian Exhibition)",
  "Duel Computer (Novice)",
  "Puppeteer of Doom",
  "Jean-Claude Magnum 1",
  "Millennium Guardian (Domino Pier)",
  "Bonz 1",
  "Millennium Guardian (Italy)",
  "Para 1",
  "Para 2",
  "Dox 1",
  "Millennium Guardian (China)",
  "Jinzo",
  "Rex Raptor 1",
  "Millennium Guardian (Canada)",
  "Mimic of Doom 1",
  "Rare Hunter 1",
  "Ghoul at Bonz",
  "Ghoul right of Rex (Canada)",
  "Ghoul left of Rex (Canada)",
  "Strings",
  "Lumis",
  "Umbra",
  "Arkana",
  "Rare Hunter 2",
  "Mini Ghoul 1",
  "Mini Ghoul 2",
  "Mini Ghoul 3",
  "Mini Ghoul 4",
  "Mini Ghoul 5",
  "Bandit Keith",
  "Marik Ishtar",
  "Paradox Guardian 1",
  "Paradox Guardian 2",
  "Paradox Guardian 3",
  "Paradox Guardian 4",
  "Paradox Guardian 5",
  "Paradox",
  "Chevaliers (Cable Car)",
  "PaniK 2",
  "Mimic of Doom 2",
  "Chevalier 3 (West)",
  "Chevalier 3 (East)",
  "Para 3",
  "Dox 2",
  "Bonz 3",
  "Rex Raptor 3",
  "Weevil Underwood 3",
  "Mako Tsunami 3",
  "Mai Valentine 3",
  "Espa Roba 2",
  "Bonz (Imposter)",
  "Rex Raptor (Imposter)",
  "Weevil Underwood (Imposter)",
  "Mako Tsunami (Imposter)",
  "Mai Valentine (Imposter)",
  "Espa Roba (Imposter)",
  "Dark Mokuba",
  "Seto Kaiba",
  "Sol Chevalsky",
  "Reshef the Dark Being",
];

export default routeDuellists;
